---
# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: rados-gateway-ceph
    namespace: rados-gateway
type: Opaque
data:
    ceph.conf: ENC[AES256_GCM,data:aB5zAAZllWLsEZC4oI1srzPfcjQKKw2B0jKLpqVDkl/oSyJ3aDCyb3xli4S5rkufP8oRwhcjNnxVPq5GfOAI4zV1XouY3FJlVcPaCXws3nEcxIdBKr3EEnMzVlrej677IzTutjMEluogZq203VTQKac5eAbFqrTdmUFtJC8JSVD1KhLcqVFKOa/ntpnsYXraGrY97RtJedROBx6qgLYKBNSTInki9HOmVuVHAWDcAiuYVM2C0lYOaFW3nzzwan9TJ/KjDzlMjRjMfyA/K6ZvPytPnKcRxOWdYPN6NCFhbdzAkG+gj/A9VDkmgm00rvUQXbH4DhKiW9Cqo75o1iW8j72Z0tr4UMXMqdY1s/vXNSSzf49v2vt8ltianfRuYVJ8GXaP5jgJYXmdS9GeFpmSdD1XnYviYF+V543Lyext4Ka2lA36Pp5dUOj6xnNhKbYd+WF1Y2c7eMOTX1OKNeX/uiUG4u2n7FX579fv7Fi0+3P3ZfwLi/P38IMK73I9KCX41fvVgc9chq9W/7KXFFnpiRpBdVfyBc4WOFfsUw==,iv:Fi/iQYkR8WQwGuWVeOiaIsmUZ76R6E8D/48VFl6Jd5A=,tag:exE7PiPR8GsPWZEzoFjN/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQmNnTCtDemwyWFE2WElM
            UG5OWHR5MXJwYnBsMjExeHZDWGp6aEp1ZDMwCnE0WDBnTS92WmdMK3lrTEtMeGRS
            b0FuN3V2elhtd2tieWpCKys4ZlFWNFkKLS0tIFB4MFhlQ01xMDJSdmNEU0xOSFQ1
            WExSYUlZclVkRE9DSnB6c3VhcmFFcmMKZyuAs1pw4mxe9/6+TbUxNzMkKCvJGyCJ
            vpSE2Qm7NB1WJ3hzFQWUqtR0ayr+A4FK9jyNG9XA/hOA1t8MfWytHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-09T18:53:26Z"
    mac: ENC[AES256_GCM,data:bFWR3gwUBl9gU0GfnEkvzkUFEvWUGEFSPh9JX7EU4jOSSzxNVzFXnGQQqwXiEkldryq8NLHzGdTwdN4Xr8SL7fe6S3MxVwLbxquWQhbtTa2Gymn1aCd67hYv4WrrX7ZvK70TNDp8V3CS7vLusDZ6ssCiHaGTAoSBG4zi3dLpvDA=,iv:+edzX+GzeHmI9sFWurFPF1DlI6cxtIhjtZVAzDP/FEg=,tag:pARzAJgzcF4nqKpsyQmsYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
