---
# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: customer-volume-ceph
    namespace: customer-operators
type: Opaque
data:
    f45ffe08-864b-11ef-aa42-8930f34d6cfa.conf: ENC[AES256_GCM,data:CrONLyRM1PkRVF97mdZLyQ01GWC82bHGacAtP9K8a724l+/QldqczD3QFTZxRR0a1S6KwkGk/maae6QeedrGIoj1VYeX1jJrB6dExS1Qif29W5XVqXd97/An81QWInq7iPmbz51McAoAnjzACiRFggabry+DxhR+sACpBrQ/XJrBzyzYSFc1b4cgK40Jh1rN4gtqn3ZuPb9G5UIOL0YrBWlDHkZIdBx4u/ZV+LOonLRfD/iE60ICXM84+EXw4Qrb1QtUse6dwbAds8BSrK0ppflUL3UBeU0HVjfkjUXcNyb7uW/fuVkGy4QGG6vkueB9OOoVPLVkPmQr9ktVwvTHulnQQhFdpN/Xjaq6aapa7cN3gjv901PlsWjbet52RdSCp28rEW9JpG+XatJtE9LqjeOM5OTvg/5lYhYLej8u9mRYAbI/lI+sAb9xpZ4iS9hTN4xpkePbktN40qrHaTqnxtd324c=,iv:UtBtyV81kO3RjgPoHk9LY2Wyir3+vizoPpHAFXlzMhw=,tag:M2ihomzM+F91Cku32l3Spw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bGhrRUg1dVhzRnRWYVBa
            S2xKb25kTmFwTTFiMklvZnYxUFpOL1lZOVhvCkdTV0R5L1dEUU1yZGZJWUJucFpZ
            cjFNYm9NV3pZUnQ1RkMxNzFKK2xsV1kKLS0tIFplNHNqN1NJSG56ZjVNemY4VmxM
            cldTTkIvd3pqeFgxT1hjZm43T1pyQTQKHuCatwChQpENnHVbvxHNycl111Gbhlyl
            Bo/jtUtnVKIMuRxd26mRbRFXyBoIZADl0DQHiOQBrIBSIs5RVvl2qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-09T19:03:12Z"
    mac: ENC[AES256_GCM,data:DzvTrh08MxPvBDhdsQFeJCtGv3TFMptT/gAsdq2tWfufOC20jOlbnPRKeburQpjvyZ/t4G0s7eo8Or94Gzi6n3JzwRMYUSL2dzr8LNqj0nL6icMzFpnt7J1Iv+N/m2iIZP3lTwkyHTGwQpH/eaj9L3btqGP5+QcSBdqkm2nitCo=,iv:2wvKeTEJhTWL60WsH3sfhvv2+l61eli6Cw3t4fCqqYg=,tag:gBorb3MFbJV6/OcAnwqmPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
