---
# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: netbox-key
    namespace: infra
type: Opaque
data:
    userName: ENC[AES256_GCM,data:M7EnzNi918ShpljL3l4PYw==,iv:t+el+9io4fLwW9uLoZJdbAKaZgkiwwaI2P8R+VQcoCE=,tag:K5BQ3bIv5OGwwnd35+es+Q==,type:str]
    hostName: ENC[AES256_GCM,data:0kCNsdVpDkFGeMnODhsH7A==,iv:PdGo4nducHAOjo/VHvUo8LmBz+Tc0Nl/KSxW+zGhvD4=,tag:stqTyq/efXAUhQMjU2D/sg==,type:str]
    sshKey: ENC[AES256_GCM,data:I/xMLZXnpLEwbDrlBvdd/9VREId8kRTo395x4040+KtfLGmZgZC7rSr/en3Ca/OWt/EaXdL/mW8RK/6/IWHSad2MiJ0weggSYyfW5F+vItbC+ugpAq9Xi73JzkLIfopeKVfN8pHa32dE06IKDVG0lDzyZrAIgtW+NikVtDNSExPD7UPkZLsYyOnY1riMt9o5Qd1PJwRc4PPpp3giANh/2VpTb9fT38RlyzXFyJRbPeElFQYKaJRxCvZSTjdHRh3bGQU603WjAo0wpEQa59xGLDu4EfI2tbnyEmudR45O3aGztYQaQJws5DYBqa8b+kgqfegHKho90ygufcKVE/RnJqeCIOvJ5RZIEkvAjH5ADckLAJtIjSjuAklb1QR6CeIjeezpEUdL4OckEbnqGMEB6WFOGzNMVFggEiwzkzzU/2MGyX+qsTCBJEcCv6fAmD+R7TJi3Nh8eVZ7HaXHa62DVbxn49kaMjA/iztN8VjlwJNLw7Z7orVJCaKtmX9gwoCAR+MnnFxxqaR7Z99m9ZQOkt2fXD/5NG4JU5gETM9ucPH9ju3YFij0TkVtDGVkmpVftCTNqv8l4YL3gERFxp1nZbGonI8pqgg9zJIbfRR3HmNAol2TISPgdedEMCbOEYbOjfXktjSKo2h9Uj1QPp52MHACCeqW/+4V+gPDqWS/oSaTEvMA0vxv9vZbF28qrAZh2xD/IK7d+FiADOQKgI6bdXEwFVA=,iv:XzhEATjT9xO1PaHL3It3GgAL1FAmRtkVmLsur4kb/lU=,tag:OQFG7roe2jO+yg4TWXlOxA==,type:str]
    netboxToken: ENC[AES256_GCM,data:793SkJIu0STAkMo3E7ycyrjg37DxHs9j0uTN3E2vMCjFF8Om5fMGgmX9tJL8EugkckW4ZvSRxVY=,iv:EMAj9dYqHVuVhgb+rE+EJntgfNVz8VwVu1ZerW2DpXY=,tag:bSa5oUbh0q+xYFBTTYW3/g==,type:str]
    netboxSite: ENC[AES256_GCM,data:kTFXIQD0HRszeD/EEnNmaQ==,iv:PpBcWYp4edV9eQXPhWUY3BxqsBynOFM8LtvXLs9QKCs=,tag:fQj9kdyBXwluFI1T6qxq7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdnNqZE41Ui9sV2pzcVJM
            VTFuWkJFN2VoV2RuUDhPZWhEd2RWZTJuY2t3CnM0SmdzUWVOYjJrQzJQZlZoRVJP
            aEtNY0hPSmMzRTJFMDR2MUhmUkFZRFEKLS0tIG1YSU0rZk5ac3lSblFxTXNSTmp5
            S2g0bWFnaytONCtFVUZoOXNFQzdyUGsKMc14p/VMfUxjyz/hj6is7LEXAWt9uD8P
            lmXk5Pmry+3mhXUQJaQr1JtRP1cxqs8zMoSAqoT+hnAKbjDD2Y3P5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-24T21:49:11Z"
    mac: ENC[AES256_GCM,data:sNUonnhkoD3ISJrnSgoIx8s5vKvInhDExLdGUrQH3s954g60R/p2w332H54/pD/e0S5rlUnA8qaN8NgMSD5lbaaC/kgnkWOo0Mip/NRXK/JTDtoDi+inY5z/zWk0Tb5v9ZJQXNcEzfANdtc0gq/rqeRyf0JKN8W8SEspx+tq+mY=,iv:vYGljcJcwwdcU89He+qpS0pOg+31mKoEY8xSTPBKKn4=,tag:3a9JHbml2XwdJr920itE4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: netbox-key
    namespace: noc
type: Opaque
data:
    userName: ENC[AES256_GCM,data:JyalyQI1H/hF5INYBgvxng==,iv:NsuluusOr6SPq/3lStORG0BUbOT1McqMlW9fjuPeHhk=,tag:zZjGEqoDUnyF7Br4mUMpIA==,type:str]
    hostName: ENC[AES256_GCM,data:5AbZGAg33PEbPF5tPwf5ag==,iv:EULGlCeYnP5EKF2ng9YkUNblWh7sp4nAs/fZtxMp3Ws=,tag:k2S4rDbSA7H2zBsPhZwTrQ==,type:str]
    sshKey: ENC[AES256_GCM,data:RLnf3ePo2BqQhTl7Qzp7vWVUMQwH/o3/FLXyOD1naYgzacd1K8i4zwQ7ixWyvSIwp2HqRtqJxVCIwogYiKzlpclOovJBHkcc8q63eDjDCJnOA13iBDq5gupF7uuNaTULZGvwxddsV+ZSQkOblVQvrbyVCSBfPeybI0i7VssI5zARADIwUKdzMWxgIaCP17GMBk3yJO8Usyra0I+cBl2evXe4twJNUA8H46BHasxd3C8TM9HHm8NZVFfGUhGSoe7hBx4UZJA90vlO18jZLHckplhu6Fx7WOur+ubHmesdfvpSp+i73/axMJPA0FfHXXq45ZF2mIqjYyPJPuKinoKMj2yBXPXVdLWcm5L2A65B8BjzDPno/I6XNnZek9eNbmpXunssl+IOdMrAERLEPS2IYXB/7y4DbchSBItK9qqVgANfrFkKuZfaCgRsJpUAfw11p4bquYvoj0Y8kZHO7EuT5pXNvn56Dx1XXcVBV+PIiMPeUMaF0x/gL4S9fYoHS+ZL4SyQpjcowA5iwsKNIOb0rOEspi/QqDSzJQi6HWd6fk1UboFj1/GZQK49tcVvIZBilxRZu0xgblTFRWl65A3yQc3MDasF+m0fFIeyVHfb+ls/vyfXQwTv4b8pQATlNQ7dylZG7GkT30GaQHAj1yYemNmWSk41uobufezs45KIzGIuVqw7+bTfdsXFFMjYZcvVfWz6zTPdMy2m7/4bRQDaDAGN1ZI=,iv:1ZfzDky1Na/6JZSw1cmYReLOhxdJVVo1HJd68Sy5Zc8=,tag:TseAKjad5Ps/ZJZwIuJ97Q==,type:str]
    netboxToken: ENC[AES256_GCM,data:TnwHg0HH+gOUxFBsqjGkHrmfQRkaOTVNIg0ZJac+0aKTKvvOeakP5gLEF4wvnmsAeatPsB5ThVU=,iv:h5PWtMpBdyomVe7NCtFVKC81c7Z6EQNc350VlxI59ZQ=,tag:e6pKogUC2Rhfy9qxUjhZ4Q==,type:str]
    netboxSite: ENC[AES256_GCM,data:Gi5hcAhXXZjX+fDy5QlKHA==,iv:yiN76edgrZsLpayr+b5aqNBVQ9M0218lK90ejyzGeOU=,tag:L8K6Wy3GhIyHDxsnbu3G7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWREJGNWNrS2UrVHdidmVr
            U2hEcCtZWW1wK3hzVDNLc2NXTTJ0dXhCMDNzClczTzlyUGxkNndEMUs4RkMwMFBp
            bFJOdVpBbFZCdFFwdEUyNWhkU2xMYVEKLS0tIGZxbmExZmJMNWRXREorajBMUTlN
            ZHJsNHpQa3EyQzY5RE1qNGlGSjU4d1EKcRFgdkDN31WJyADTr+tNyQHM5NSzmhCR
            xbQElNSbGO+wNqDMyKUQN/jAeRwB6TrgXZdRVaf6+6eP4dPU1G2GLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-24T21:49:09Z"
    mac: ENC[AES256_GCM,data:cnwU6RJn1D9xkVBw0BfRW8PFfQluPoFeUY3S5Eu2Qydd6qvQICdZMKc6BusKd7fdSw/kXiKCLKMZSZTo6GB2ESm0ZnU35GZbOvpgg2B2xQ+T2SdSsCEGrrypjDl+q1bvQd0nJ1lMEEN4OIRAIMRkh3EDVAm3W0iIEZ1J8Go/MHo=,iv:Cv4B/Z7IvF2sNB+2lDr5aoMKuji1hcPaOyTGS66+Tsg=,tag:v7AtL/CERDCCUAL/lRIhTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
