---
# yamllint disable rule:line-length
apiVersion: v1
data:
    auth: ENC[AES256_GCM,data:PKXd8rQd4cps7rytvDcXal/pnVZdIgKSAOnuGhh3EgTZbAsYlFK7IygbKIcjLjvEMABpRL8KGaQ=,iv:gsy8gK9SnVVncSB4GQBV6eY0XZ9jmV8/gZA9q33QUT4=,tag:RBOpHxu9fOEkosWF4KUorQ==,type:str]
kind: Secret
metadata:
    name: northbound-api-credentials
    namespace: northbound-api
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TDFEaWROeHZUdEE0QTdv
            T3h4TDRZQlRvM1djbzBLVit6UGFrNEZRWFdzCmtybTRJMTVIYVRpTFpwN3RCaGFo
            VGJJSmFhZERQMnRuL3QyYThXUU5qdm8KLS0tIGNkTzU4cVpyY21mNks0VGxsOUx1
            Rmc4cURQZkVDVHRLcWlMV0JYMmQ3Y2MKL8g3/ZpgAZrXvD/A0DkXXv5blw9QrmlW
            g2VMK/zr3nzhLCt0hcD5aGbcoR2pTf99bg4/fgq/rJ/czeNuCvwNXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-07T11:17:24Z"
    mac: ENC[AES256_GCM,data:2PJ9LpxvpKUqRsHEVtvrqIAph0FYJ1Cb+ssARoEF1qM8jvU8D4Hylxg0uspHC5wGqibNMIsifHREE/fb9UYa9Hvc3H+3WJHZxdoRjJ997UdHFak+JHBDGm4h4eqgICLqcP5wDqv7YWjRMftnD5DyF1snLJBoj35tJKZatWIvf4E=,iv:72/0arBwqwLoabmPwpKgifI3GTdmaCrxS6cWdeZ9d0w=,tag:4OzVZq5cE7MivuUKzEgqUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
