# yamllint disable rule:line-length
apiVersion: v1
data:
    auth: ENC[AES256_GCM,data:NPXf9/7SQQMBFr/tw9hYkEfuQ6c1kEteT1nsvVKp/9NyXeiYfMCqctMGl4ZCUe3NYTar2KAsJU6bAFNy,iv:aNZSyEm3hXvZSClvrKO1+ZZshApN6cqp/BPcu+Fnn+Y=,tag:XrhONIxEEV6Sn7mXL5gy8g==,type:str]
kind: Secret
metadata:
    name: prometheus-basicauth-credentials
    namespace: prometheus
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSXFyQjYwWTB1bWx0aHoy
            dGlHRGFYVTl4dWhoUGV2ejJYa1hjaXVPM0ZFClU1bW5JdEtIZ0VCRzJhVzNFYTRj
            MVRhc0ZlODNaZ0huWmE3SHFPNDg0OVkKLS0tIDgxUnpLK1RZOEpsRmEyQkhiaTFs
            V1gyOG0zblUrUzJ1WHVYb1JNS0hmMzAKy3FOGbA/IwpjOo4c9d1KxL7TNESpAy7I
            fVEGhjmMfWjfOJaLnO3AOJDN7S3LSWOg0CxDbiDekv77so9DgtzWpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-20T09:49:08Z"
    mac: ENC[AES256_GCM,data:fHjKE2TlI+NYQmAirdJyMJ5vnfHF2Jah9OKuhovbMeouqr0bk6wdZjOlmSSYZvA4bsQGjl2ET2+rtqDEZ016dhbxKf1vJAKqHrBRw8CnADylGBCtxDNnLkCslzxgZ28odzBxD1q8/Izk4hWXNRCkaGchieYrWt5ppoua9+LGSik=,iv:tcv/reESkeeddct4GrcM4KPnpabxVypF/f2nTgl4hMA=,tag:Fs3GjX8+DYIlJIqC2TKXHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-slack-api-url
    namespace: prometheus
type: Opaque
data:
    backend-v2-notifications.txt: ENC[AES256_GCM,data:jAdsKdsnU7nRMu8OUUXX/5E1nYnXTWRxPJZrK9ewRC4wljS299J3oatLR68vWmxrayG863kudrJMd82LJFr8EglR62QeRRK+SKQzHLHaKswu5cK+G9X2kavrcIdF8rRkXABt+Zm75VOMW8vU,iv:uk6Qt93VwL13aJHb2qbEhSXU6wyAfq4lrWnFA5X0vSw=,tag:gOFkL967Yp6IqyIj94/dgw==,type:str]
    gws-b2-cleanup-notifications.txt: ENC[AES256_GCM,data:JVRhatzAfSFhJvi8CiMLZLOi3YB5sHJpSEjIZymCRQdrOWABlC2SQA0KKnO2sYGhBqSinBkcCMEKW2c2WT9PURQvjIYSF2RvADtfaTkx5GO1uHblNAqAdPmrfRBcEvRPBx97khMUhuOjUCmi,iv:kQ9BqPsBWBIFgxnStL8wlEgBJTp3nVQnzdz+2GdgFn0=,tag:9A2DpxvvDioUx5hvuugAXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3a3hFMTZnOEl0aFZ0cGlL
            MEhHczR2eWh1R2k5TUF5M3I2UmljZy9lU3o0CkpEamZrcDdSVjMxd2Z4a3JMeU5Z
            c1pUWXZHWjQ1bS9vN2ZhYjR0UjRrQXMKLS0tIFZJQSt5K3E1Tm1oZUQrTjN0SUNF
            cTNGRUJLanhEeHBMeFh5dStGR0dnMWsKZxom6aCey8JQmvwN0acMjCITPPp2xu4j
            kRUbcf81JvgvHQz+zdEBiV8qLTDmqsJU4E/StMIx+nbJ4yfz5tdc0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-04T17:11:57Z"
    mac: ENC[AES256_GCM,data:MpjFuNSG/TwrTsbxX5qd8RLQOvcellkN9yij+fJ8SqniRwrgrc+OCg+WFuEldWtdsWJ4Gi0nAWx7UhJZwUBaJ6JSWWpmb/FnuWYLSAmZqudpQ9iTr/eCDchQC26LOrgif6+oTcH16WeCaA1PYfrwqas+sHFMSap9bd+x3ft4MdI=,iv:A9TVl/4u3ZJviGhLrBsNY6lmjKC2jcluV66F2qfvoD4=,tag:3DvGD+YambLdO3ULBW+BAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
