# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: public-dns-key
    namespace: customer-operators
type: Opaque
data:
    config-snippet: ENC[AES256_GCM,data:z9dRPe79WGBEyg0PRSeAb1jG+ZOkdm623neESQu+RojxEMmydzniQqeABvcHEDXYYk2LYf5am83Y56Et97cdApoY+IUFBuYwR2nr3CM+shiMZRxDzxTWTTEl7EsBMtzA7Xnauc7Ie05z1jSQh8bGiEM9RYD3VkXWWR0jg9z5G+5zQBGQFBDmgNnrmCKHE7abwP1ShVecHJP8Se7c2ZKxZJ6CBH7BuhlXvzDuazuynLkA2SQAwkJdqMcYde7DNNBqEXmms/VnseVniWlRhwkPOmfz/H9UOnqYfZEZD47CgaA4owyzX6HfT104BPhMbAwynUEeF5NJOFaR+y+8ZTNgLd+xC3G7LGh6Z6aw9LK8LVoluE9rZIWstNREx4O8q2iB1BRo9SxFG5WHB+GPT9fmgVGLN043pw5i2S7pPwzNYzl5VtA4yhcj75i3Otm9hOuzbcsDf1zlBLC1QTz/NJ+MDwmA7g0QEWVIdWELtyGnTCga3euUCtswA3jmCbB85+1IsB0KoO1uBPebDZZ1OMOEbtpBkOf7fUkSTEfLuj0eKjTjjAwDvJG909VnVpZvt0zfGbGLhGxnEgV605B+0GL7x3B9bFrFrpr3S5ZMHi0w+FvaqGyWOfcVpwSdUnuZq+UkR+YtIQC8P5mLZ0N9MsWGMZNlEZEVbg0+IyBY/kaqy3L4QdjJxAP8daObw2XLpmf/NFf1qOirQFxD0o3ubSQp9t75OuBOwbQ2hN7RS3yb1bMi9w5VLcWIM4qIFbFnoElPK7Jot2i9kJd/31H2V4HqCeSjsKzL4wXb6CLUkZAhMT/Z/NqPzPeeL6nshFkVcXkQzVD+VqYYGRhj+9VdWty1/Q==,iv:sluNSxJZlerlPHUJsXFnNaSNCksHk9h/dobi3G/DrbE=,tag:PVS6SNa5czPWtHFBfXfecw==,type:str]
    secret: ENC[AES256_GCM,data:sUj/RvXKUOJbLDUCNmfUJtAG1lnYamI9ZyD7UieNfn9B+DmJ4IT3UPgBgCfhWnVcFtYE/e7eOr42lJt3dVEz+Fip1IbhDfd9rwgzwz3Ubyh/KnU69fo1601D/p4Cj0dWG0xwRVLYUkjZnEEf/DgIFxjxLvtzKskGjp2WoQ==,iv:BilimeDBnwb+oq9b0QN4RuQeXWteWgsDePkJTEPQ9VU=,tag:isaHHDKXVKsDk9pyk7E1bQ==,type:str]
    algorithm: ENC[AES256_GCM,data:rlj1eHjYIPMGxpCG1kmMwg==,iv:RAfJHWpbq6GW13UKZUbj3RA3e8/LvTIxxrhynB3ghZg=,tag:v4Or6qx6vzRCeBlpJWc/cg==,type:str]
    name: ENC[AES256_GCM,data:SWZmL1vkD/F1E0nv,iv:Q5B8YbuT7pvr9OSIEp/WFGakZD+irRC5kM21N8tda68=,tag:YAq1oLkdd1lqHpvW6tf/ww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQ3NpdjVtSFh4dVhsTHNX
            RGc5UVpwRVpUUTd6K24vZmh3bE4rcTJDczFVCmdoQU13anA0ak5iQ0lycHJLMWtz
            VE1PaStIOXdvcWdsbXprVThlSCt2NWsKLS0tIFlsUjBKR08zRlY5bWdTb3dVTEo5
            NHV5ay9taEtxMHU4MzBFeksvNkx5Y1UKfFgXpzdddsP/ZbV4NALjzlGXyNT/t1IF
            SaGCWfpzHkud/Vuhw5s+pb8qz5Rl4hnsNoDGHBHlPbyEpq3oYhk9Uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-23T14:35:20Z"
    mac: ENC[AES256_GCM,data:ROnGcEUMVHGL95SvzL/7p/KtBWh0toGFrcnByQygXqt735fdNYlolAPwtmaii/jmL2qn8bRlrIwVyXA5Ia2O1t4EmJ4kD4PAU8HVxgdqyKBjmpcPJhdQFnzzALwIJ2buk1/eNEF27oQgLlnsTr+Zkef1U8cJjtu43Hu0cVCbKgo=,iv:ZLNkxUlOLeRPPnhSrPaJ1n4BPh3sE7Z1CmsDl6A4dHg=,tag:On/qL3MLF373qpdTxQeSuA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
