---
apiVersion: v1
kind: Secret
metadata:
    name: snapshot-presigned-key
    namespace: customer-operators
type: Opaque
data:
    key: ENC[AES256_GCM,data:hSEa+yV3QDRW0NiR6q+zMU1ZOaneqiMXRESJaTWFWtRA715OPxjCqOETuonLwkxy+4cGkwfPtEK2A6dl/7b4/2eBM1l4A5jq66zEuk4F2QkD1BiAuxtFU90gLZ4OdeM0ywLhwnvHEaWYovJ5/zYWNgeoWmtfTYAWGKm3HYzMJRTk2mk8E+id60KJ5IOoIb5L/8959NlPIe6VzIElFaH9MKcD5jYs4Vb+CmgCIz8wSjvtkp6kmqqdkxqrW+wkJxgah5zV9tlU/2RjDfog53m2VZPSifnFZSX/4jqrsAgnnZgpb//rmUCbOy10C+YjDo3/mq6uE+AXPZeISbZm9t3n0v28I3kQpKy3hCyzNg==,iv:9IzgR46bYQ6RhavBipiNnK+Xk1/nGOYTnlLk1DMfuPY=,tag:x/HXGiT6XgNdSCsfBIq5Tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQVNDVzF0N0xqUy8wWGhR
            OGNBUjBaQ2d0MksvUStGYzdpU2NSVWNvQkFBCjFkZGNXNTNocXM5WWwrOUs4Z3BH
            YWFLdXIvbW9mTVZqcWd0dmJzQ0NzQkEKLS0tIEdvYlAwMnJ4S2lia0hRWnJPYlBu
            dld5Qjl5bGpZZjB0WGFra3A1dmRtUEEKE+9q5gsCJcZ9DzDkHd39iOhnUrJa0WNB
            pl8AxfDj2TBR/zKFaWM1u3vrwqXlY3ktizt6fVsi4ExEluSk3mvigQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T15:53:29Z"
    mac: ENC[AES256_GCM,data:tWELp8zDFGDVNjmGocMjE3J2KYiZkyGMSDnmphj1K+O2ItKZJwLtw/n9i0qZORv8/3JcuP5EXvQI5mBnqHneK7PJp/Zm6JFvFKUf74WdRwkxp82j+kJDpSy85sP4sOQv71i28HF+b5t5jJU9pTNMRfLKaLyviFF7vFH/DBjxNSg=,iv:PWlUeSMeKyapPpXcM/bXpmlql0DJE20cS7znmsS28aU=,tag:KMkryfJZ1knu0M7XqAQwvA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
