---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../upstream
resources:
  - network-policy.yaml
patchesStrategicMerge:
  - enable-feature-flags.yaml
  - add-gpu-types.yaml
  - tolerate-control-plane.yaml
  - tolerate-compute-hosts.yaml
