---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: grafana-configuration
  namespace: prometheus
spec:
  interval: 1h
  url: oci://harbor.harbor/ghcr.io/gc-private/b2-grafana-configuration/b2-grafana-configuration
  insecure: true
  ref:
    tag: ${grafana_configuration:=0.4.0}
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: grafana-configuration
  namespace: prometheus
spec:
  path: ./
  approvePlan: auto
  interval: 1h
  sourceRef:
    kind: OCIRepository
    name: grafana-configuration
  writeOutputsToSecret:
    name: grafana-configuration
  runnerPodTemplate:
    metadata:
      labels:
        b2.genesiscloud.dev/allow-to-apiserver: 'true'
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
  vars:
    - name: cluster_utilization_config
      value: |
        ${cluster_utilization_dashboard_config:=[]}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tf-runner
  namespace: prometheus
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tf-runner
  namespace: prometheus
subjects:
  - kind: ServiceAccount
    name: tf-runner
roleRef:
  kind: ClusterRole
  name: tf-runner-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-grafana-from-terraform-runner
  namespace: prometheus
spec:
  selector: app.kubernetes.io/name == 'grafana'
  types:
    - Ingress
  ingress:
    - action: Allow
      protocol: TCP
      source:
        selector: app.kubernetes.io/created-by == 'tf-controller'
---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-terraform-runner-to-grafana
  namespace: prometheus
spec:
  selector: app.kubernetes.io/created-by == 'tf-controller'
  types:
    - Egress
  egress:
    - action: Allow
      protocol: TCP
      destination:
        services:
          name: grafana
          namespace: prometheus
---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-tf-runner-internet
  namespace: prometheus
spec:
  selector: app.kubernetes.io/created-by == 'tf-controller'
  egress:
    - action: Allow
      protocol: TCP
      destination:
        ports: # needs to talk to the public internet
          - 80
          - 443
