---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: datacenter-collection
  namespace: flux-system
spec:
  interval: 60m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./collections/datacenter
  prune: false
  wait: true
  timeout: 10m0s
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: ConfigMap
        name: version-registry
        optional: true
      - kind: ConfigMap
        name: grafana-configuration
        optional: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  patches:
    # Disable inventory sync for the time being
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: ignition-server
          namespace: infra
        spec:
          patches:
          - patch: |-
              apiVersion: batch/v1
              kind: CronJob
              metadata:
                name: inventory-sync
              spec:
                suspend: true
    # Disable dns sync for the time being
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: dns-sync
          namespace: infra
        spec:
          patches:
            - patch: |-
                apiVersion: batch/v1
                kind: CronJob
                metadata:
                  name: dns-sync
                  namespace: infra
                spec:
                  suspend: true
    # Disable dns netbox sync for the time being
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: dns-bind9
          namespace: noc
        spec:
          patches:
            - patch: |-
                apiVersion: batch/v1
                kind: CronJob
                metadata:
                  name: dns-netbox-sync
                spec:
                  suspend: true
    # Lower replica count on replicated2 so we use less space
    # Duplicate storage nodes as patches[] is not merged otherwise
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: rook-ceph-cluster
          namespace: rook-ceph
        spec:
          patches:
          - patch: |-
              apiVersion: ceph.rook.io/v1
              kind: CephBlockPool
              metadata:
                name: replicated2
                namespace: rook-ceph
              spec:
                replicated:
                  size: 2
          - target:
              kind: CephCluster
              name: rook-ceph
              namespace: rook-ceph
            patch: |-
              apiVersion: ceph.rook.io/v1
              kind: CephCluster
              metadata:
                name: rook-ceph
                namespace: rook-ceph
              patch: |-
                apiVersion: ceph.rook.io/v1
                kind: CephCluster
                metadata:
                  name: rook-ceph
                  namespace: rook-ceph
                spec:
                  storage:
                    config:
                      encryptedDevice: "true"
                    useAllDevices: true
                    nodes: ${rook_ceph_nodes}
      # Disable public DNS for now
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: customer-instance-operator
          namespace: customer-operators
        spec:
          patches:
            - patch: |-
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: public-dns-primary
                spec:
                  replicas: 0
            - patch: |-
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: public-dns-secondary
                spec:
                  replicas: 0
    # Disable netbox-access for now
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: netbox-access
          namespace: infra
        spec:
          patches:
            - patch: |-
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: netbox-access
                  namespace: infra
                spec:
                  replicas: 0
    # Disable rados gateway for now
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: rados-gateway
          namespace: rados-gateway
        spec:
          patches:
            - patch: |-
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: rgw
                spec:
                  replicas: 0
    # Disable json exporter for now
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: prometheus-json-exporter
          namespace: prometheus
        spec:
          patches:
            - patch: |-
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: json-exporter
                  namespace: prometheus
                spec:
                  replicas: 0
