# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: rados-gateway-ceph
    namespace: rados-gateway
type: Opaque
data:
    ceph.conf: ENC[AES256_GCM,data:sEQiUwS3uNOAjAAGWSc2E6uxRMX9uQMCKl3wECrAlytHBOO8lwNWwHjS0i582x71f8iIGTcTQ8EjEwc38ZCOUN5n27VGfnU8fksEmNfbMHQj3dhtwvDUjX3Ak6zhn7c+KEeKAOkCMSt2QqHAL+iLI78PHxLCW2Yyrxrt+xe77xVh4bpAJpa3ZLyt/YJEfgExAxPlCIXAxXlRf4LPdv7S5HSYU8R0WIgSpdcMTI9m3KoWT0zGjS1Zm2v//weOE0zcT8EHPthHW6m42AW9QMRNd+fR1QzQrpHHVLXJ7cpdkTnOGepknwpoZCIeJ4Iqltrzsk2Xug==,iv:n0oU4ouhjOZEgx1xHTDQuHfEwiBAh5K/mYFGThhdFvM=,tag:WvleftmAPle7VFyM5bZDbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcTNjeHp4OTJYZXVpbVRO
            SkZwMy93UG00cGhERFdQMVZYcTdUcm5YakRJClBzbXRXOW9VSlhPVGdnQmVEUUkx
            N3M0akQ0ZXdydDhSU04vZGM4TUQ2cnMKLS0tIDZEUFREUlY4TTVaRXBMa1NraUto
            cnhnTmplVHhYZFArcytSTnhYRTNDbkkK0Q2tF6obxMP+Ka0KnVOI6tWBLYGxcxWw
            F+Xx63YYiEYglj2jjvJaf2Z6lZKQWsBwfZRddruBK5nnWCXzp8JD0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-02T20:59:28Z"
    mac: ENC[AES256_GCM,data:NehvkWfPZLQbFLpna5jA9CgRjhbTSCSamG0tOudOE6KOopVa7W4Amk5z9P4HIa1hsnoIVkTG+n5yOb2vxqKjQ7Nb78vMQavZODuF5Obqvt+UTsbU+EDvDnJBKhttUYw0yUTIvxI9+yyVGNctWotVZimQMQvqiNTv4OeTjhosemc=,iv:DmLgp7I5EI0b8DDc8vsSohZKZlCUulFMT9FLp1fXxDI=,tag:wQNcOBDslWiNPYAeHnvGbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
