# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: customer-volume-ceph
    namespace: customer-operators
type: Opaque
data:
    dfb88bd0-836a-4d2e-b3c7-e5d0dddde6ad.conf: ENC[AES256_GCM,data:qWNuyKkmjzgGw3+cWiZMx9YpvzgbifAc16efhHwkJPVMqBE1fmJexv3sag9bihvp0IzWuDjwios8iNUeIMmAPrGsPE8tswIB1lOKn/RKsxmvwi/CRgnML68/GMk6disUBsyaWZ6BWMihozDYq28k2AZNGKOP6orKjgX8J2sWMvBN/OkyxbEWMpZIMirLswQyg/5bhUYbksiLRTa8dpki2+iq2hoNKchpnmXskNu8N4qvb3Lw3WAd4FYmPvzdsPpz67Ta2gdaMxpGZYbGRI+hjEolWijiS8R+9yU0saLbvguvk85GhCSNi/3sdgQ=,iv:hqfHhtYmSGxFey1yE0dqcocZjo+uEt19DGhC+lPQ/a8=,tag:ZkEXwpcfezJTjKcxSaFHkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxK1c4SXh3Qy9vczkzUlhE
            TnA5TUFWckFiRi84eGNtWVNaL3c5QnhIMENnCnpqWE9HRWZQT044UXgyKzFtVVBB
            Zm5xb050dW5pN2U5UlBrYU5nd0taa0EKLS0tIFhiZ1IwZ3NsRlFic3RuMC92UWla
            enNGZTJWd3lNdVhjMGx0M3RXdFpFd1EKULPEFkQAegawuknCJ3bS4xW4v2rD3xOn
            OXCQd7sVWlabcEgjkAPjK4IJ7GtBOsS9Q5J0ZWBrXacZHWE0zpqfqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-30T15:20:53Z"
    mac: ENC[AES256_GCM,data:sUiX7P3ME2AUEvO2Nzdqk96FkkyfBMtCx++ZWMtJfgNoaNNqyC511fn0A6GLg63jLFbOnPRy8j1axGIrMuInPXtun3Y/JlDhDcidIAFUanjrWXEXIg+CANwxsMBp6n/+dZDPSLGNiWJnd6cSN4tZ9r8YNKhIrgrkf/jAmupsd+s=,iv:1GoNzSo0Aw2wQy/uQkXM/Uqyrt86T4RdY5GD97wiEcU=,tag:JVicWs8thfdWGLRSyDI81A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
