# yamllint disable rule:line-length
apiVersion: v1
data:
    auth: ENC[AES256_GCM,data:j0DI4QeLz/FZNrj8sgplu2c8Vt1c20HhefDmAzPhgEghU9XcDucsnhTcTDZlSl8q/8Oz12q0cUo=,iv:2fQl6U57117C0q/nr8i9vZdcby8+OFf6jkhHEzEOH3I=,tag:InWEZfsxoAl3NNApdfD5eg==,type:str]
kind: Secret
metadata:
    name: northbound-api-credentials
    namespace: northbound-api
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRnNGbEV2bG5vTVNYd0NT
            RnB2ajcwTFROTkxuU1AyMGo2UDZrM21RWW5BCnJ4SXZJS1M2ZlR2VmVPN1ZVQ21p
            UWo3dWxxR0EzaWJkMmZydnllNnM2TkUKLS0tIGhzUG9STU53elM4TEhnT2VYMzgw
            dllGTUJ2YXNBNDhlVEZHd01ZWk9yMnMKjMvwkq24TLKrKXmVmO3ibibIKYgyv992
            sM6oycBQegGd7DnUSmhomTX4LFLkQTqgQc8VAH92JjbnJQrAWrcHkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-05T09:45:40Z"
    mac: ENC[AES256_GCM,data:cLl3+qNUvrw6rlZMver7qrx4q6DRvg1cFUGGBbK/MV4YebPGmhfZ06Oqm8A8xGT2VeMK9GNmtauMZ4PLlyNM/LEvzUWB2ey51O22Wl2dO62aZQL7l2hDpFf2EVVOGNfWtDWrkgJXsPBWHzjCxuOPxSiv1LsbRZshVh/jMbm9yLU=,iv:8FICAOodeUVv3gN5QIBxgZAMDUO4t5CM6Ns6H44mBP0=,tag:kMtgMyfTutnLCggDuuZHdg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
