---
# yamllint disable rule:line-length
apiVersion: v1
data:
    auth: ENC[AES256_GCM,data:493qr/srNWiH6m5XPGCb0Yq1GKM6stjaVAMd7fggM+AMfaRpBUbFelJ/d/E4s6c4rajT7g==,iv:zt95s3l3gBNM/fWHecmwSW32XBozs9dnxhXKn71oPwU=,tag:1VK3epeYCNyIxRkPuyvdjQ==,type:str]
kind: Secret
metadata:
    name: prometheus-basicauth-credentials
    namespace: prometheus
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZjdBM0k4MVVRaXRFaFY2
            S0dkVFh2ZkdZdk5mOUxEVzJjTEJCQXpFV0VnCmRJUXdlaWdkS0NqUEhCdWx0dGYv
            ZThSblgzL3dqbHpZYzZkZjA1ZlIyKzQKLS0tIHFQV0ZHRmRvVk5QRWFLaUs4Y0o4
            dnYxU3pjTFpNdWNLbzVjNHlQVVRBdUUKvOaqQg2LNZKT0etG6GoQZ5Qeo5TFz3rk
            u+DaRiXQdW69KeJ9JUQM1NsDH0kJWkw9cFh8Bw3K487NDYvMh0+E8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-05T10:03:32Z"
    mac: ENC[AES256_GCM,data:eMl75k13uPMAQo7/TryFoKmlmfi2w311sOVo7EZhYguOI9hwDRsaNbd5J7bML2l0z4mnSKYqLXyYhvf7JIX6HVRASRDIdXSpN+LDJtIlsDKwdryF0Iwd+HJunXJ+AETtAdObY/km6khh6cnZkjALJyehrfp8vm+jYkj1maF9ZsY=,iv:/KQdRX2m+aQZqpF7T/bwiSspK2htZm3tGLDuDoptoXc=,tag:5aYPNcjj3FlP+ExRtzPuHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-slack-api-url
    namespace: prometheus
type: Opaque
data:
    backend-v2-notifications.txt: ENC[AES256_GCM,data:2NujsZm9Tf/3gHltvS3ZKEWRkchT9j7nRuxLvd0cPelBMP/BFCQtER2pQwhjJGMxJmqiQX9KyNzKzNRmv6Fm46E5/1ZAEDH0fUuP6HVxmM7T0FlRTYCAm/XVKpkLVcS5tS4xWPOt7WK1Pxsd,iv:8SXZ6TRqydYr8x4pcSzwuniKRtKiMsafTTuBQZdyL0I=,tag:890tTU0aCYuHKEK0GFvjOA==,type:str]
    gws-b2-cleanup-notifications.txt: ENC[AES256_GCM,data:FOBPX77tqFdHPYqgTv08LHQ+bMWQcJH/IVXZCOnhPYK4DrzpjjnEMf/hQ8XHeFA4Co4GfA7lxeuYRw3o5T0m1gB1YfucjMyVJAPuXpskQCTPyfGpUf4GFhvr4gu4tHZ9LGLw67HBPlA6mbjc,iv:nkEVtXXJE2LWgGj9iQwznlLHvVDPRPwFQcx3LnM/Ji4=,tag:it9ij9NGyl9pQJJ7DQxvOg==,type:str]
    rook-ceph-alerts.txt: ENC[AES256_GCM,data:qY8zXhjZzMoCetml9X6E1hcXDz2OOcXm7xLg1YaBYIfZUgykv1BK3OXAV8eCp5pIKRcJsc6ItB8cH7UOEETIysYu/WewdKmh4K5yu/vmXQe7Wum4pIPcEXLkX3W9k8bju2IXiI0yBcr1reAr,iv:OKuR0leZ3650h5GM9AqMBY7r8cqclOzV3vYETs8IYk8=,tag:PBKHfNS/EQ093xRfLYlDWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZStSK29JVmN6UUU1TTRv
            Yk41OGg2bmtzY0NkYitKdC9iTGNpOEdMN0Q0ClJwaGk5UkoremEvOUZ0K1BTVFl0
            UFJsK29ab2hHVWRQbnJOY1hYSXJyRWcKLS0tIEdXbVkydFVYQ0dWQlE1R0plYTAx
            WndRYW9pR3JnOHdmb3pndUZoL3Y0ZzAKXRWmKBIzKuMT499Cg2J4mGEoZ5eDsuqX
            UBX8jfnIORijZhmWQc/fe32g2GAZ7vKhe0XCCe2yDMfHnDbo7M70Tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-05T10:03:43Z"
    mac: ENC[AES256_GCM,data:pbrKXUs2SrzAh891lXGzYXGN8SZWOUz7vlhDaqWum/X0ShU/2G/hKdpNTixTyXsMmRT3qyZE9AuSy9sujybhQn6Uz6njVe6X+/ReOY15NhR+ti1q+L7s6mOKdKohkYZzZTW/0v3/TJFJ3HkRAz6DslcRKUz9dUtIYM2jkOYMyYI=,iv:oESUdNKsYdDTPDre8VporyjnMuY1vCw10cGXG+0oay4=,tag:kOhhubfF1necJBZz7iUbAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
