apiVersion: v1
kind: Secret
metadata:
    name: snapshot-presigned-key
    namespace: customer-operators
type: Opaque
data:
    key: ENC[AES256_GCM,data:KSF+JsOUUrVSsYGiZCPn/QeUGscwks44J+qqcxWPePM9vY2gXDEHBbNj6KPcHe3yVd1D4x+66QAZUbOUQIeL983O7LMetomCAi+gqMzQxGoeLe3Rs2ZpKUWj1KM1C9bvXsJBtv+Y08hqi0KkSu94dwbB7PVBEFo+fH6M1cE4kiQ87UgB73aAyD1JZtmL0mmeemavvNam21n8uMbr9K31VnaDlojF1kLf7DeC//N6f67YCZDodiD6bGPtBb3vHf6K46RwvSGHILmANut5Q3Dn/4n5+IOBAe0pIKZaD/xNrCjBAZzgO6IZZ39ngA6omOExztUQwGwmUMjSVQzBDqlOmv4lLgJ0rdbriOR9MKeBWgM6pCmG26L3tPlR+C0Nk/9yDtkGtzEYYtCGMs5Pul5VrNe9VzL91kRWkHmKvSea3Q1K0fAg1NibpnN1fhEi8Nmd,iv:z1ltolb02Pt79XB9wKYL8792J9S2C2u3rY77UlfFLxk=,tag:a11x9mGzZF/4fF+5Nifjdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBazB4UXlOUmh5bDJWN1k1
            TlNhNnFOZWhlWkE0YXFweFF2RW9tZjRGTHlVCjBxeFdmbmkzYXFKaHZuSGh1dmlN
            NFZxNUJUckVuTlk1eFkzRjI2NmJYSWsKLS0tIDJsY0d2bWFTci9zOStMcU4xaXlp
            bUFOREpZcFR4a0ZZd1dza01qMmNJUG8KMVriKAixdzePZdcqTOEpR+apqbkmBcpt
            zAoqh/0f7nvHA2czpKwth93IqaOtS6BULBGT/Doz9PqQSfE7RojFHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-05T09:23:56Z"
    mac: ENC[AES256_GCM,data:E4ibiUX2WrGXV6Fgp4bO3TSRhjwxgGZf6FhsxXrdzIyIyC4hmxI1qBeQDVn4XpNV1aZDGI4h80APUnxUlvTjxPBIicjk0OBNxl67nwram4FIX7R5RNvbix7+c/j26iH3oyhXwlEp2+iA1DHPY5/nAu1iai547/XDv3M4gCvNuug=,iv:jo1QXPEjmTS2JLfBuVFJDfIPVJfMFqo737mQCyY0VjE=,tag:occ9V5sKo0eZp6kaoNPX1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
