---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-config
data:
  environment: management
  base_domain: gcdev.zone
  environment_flag_emoji: "toolbox"
  etcd_certs_location: /etc/kubernetes/pki/etcd
  etcd_backup_sc_name: "standard"
  pypi_backup_sc_name: "standard"
  ingress_public: 147.189.201.42
