---
apiVersion: v1
kind: Service
metadata:
  name: flowmon
  namespace: noc
spec:
  ports:
    - name: http
      port: 5601
      protocol: TCP
      targetPort: 5601
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: flowmon
  namespace: noc
subsets:
  - addresses:
      - ip: ${infradev_flowmon_ip}
    ports:
      - port: 5601
        protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: https://oauth.${environment}.b2.${base_domain}/oauth2/start
    nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.ingress.svc.cluster.local/oauth2/auth
  name: flowmon
  namespace: noc
spec:
  ingressClassName: nginx
  rules:
    - host: flowmon.${environment}.b2.${base_domain}
      http:
        paths:
          - backend:
              service:
                name: flowmon
                port:
                  number: 5601
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - flowmon.${environment}.b2.${base_domain}
