---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dns-bind9-config
data:
  named.conf: |
    include "/etc/bind/named.conf.options";
    include "/etc/bind/named.conf.default-zones";

  named.conf.options: |
    acl "trusted" {
            127.0.0.0/8;
            ::1/128;
            10.0.0.0/8;
    };

    options {
            directory "/var/cache/bind";

            allow-query {
                    trusted;
            };

            allow-query-cache {
                    trusted;
            };

            recursion no;
            allow-recursion {
                    none;
            };

            allow-transfer {
                    none;
            };

            allow-update {
                    none;
            };

            // forwarders {
            //        1.1.1.1;
            // };

            dnssec-validation no;

            listen-on-v6 { any; };

            // We shall manage the full .addr-in.arpa
            empty-zones-enable no;
    };

  named.conf.default-zones: |
    zone "${environment}.b2.gcdev.zone" IN {
            type master;
            file "/etc/bind/db.b2.gcdev.zone";
            notify yes;
    };
    zone "in-addr.arpa" IN {
            type master;
            file "/etc/bind/db.in-addr.arpa";
            notify yes;
    };

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: b2-gcdev-zones
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
data:
  db.b2.gcdev.zone: |
    $TTL 86400
    @       IN SOA ns.b2.gcdev.zone. root.b2.gcdev.zone. (
                        1               ; serial here
                        10800           ; Refresh slave after 3 hours
                        3600            ; Slave Retry after 1 hour
                        1209600         ; Expire slave records after 2 weeks
                        10800           ; Negative caching TTL of 3 hours
                        )
    @ IN NS ns.b2.gcdev.zone.
    ns IN A 10.0.0.1

  db.in-addr.arpa: |
    $TTL 86400
    @       IN SOA ns.b2.gcdev.zone. root.b2.gcdev.zone. (
                        1               ; serial here
                        10800           ; Refresh slave after 3 hours
                        3600            ; Slave Retry after 1 hour
                        1209600         ; Expire slave records after 2 weeks
                        10800           ; Negative caching TTL of 3 hours
                        )
    @ IN NS ns.b2.gcdev.zone.
    1.0.0.10 IN PTR ns
