---
# yamllint disable rule:line-length
apiVersion: v1
data:
    rndc.key: ENC[AES256_GCM,data:LaTNOCbfegR1G5mq5YaOuRaoLC0SeFa69RFT8xEznt9D5dWMbOXyL3tPmDp309dUMJ/GBoQ0pO1YJDpKFRNI21kT4SR0oR7g5o34g//Ldg58UDsn4pIkTGoWfklfwOvq0aOhqV+Fk0GAx2owLNtCy/B41J+FoAevHyLC+OJS7J0IGMZi,iv:KEFY3pnpHbd78mW4Q9OUfs1sBZDAP9FXmW7xlNxgboU=,tag:eq6/USnH+OtuYztj8kZUUg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rndc-config
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWFNySEdtYXM0Zm93REZK
            UlZrY1kwTlV4NVRWVzZITmJ5MXhXZGJFaTBvCkVHSVk3OFh0WWFFRXhwK1F4ZXZV
            N0d6MkdqOStzR2xrcVcrNW5wM0lCY28KLS0tIHJRR0MyZ0tJZllUSEtQY05PWWk4
            a0xISlQ2M0w5cEIwUHorNnUrenNJcGsKCGyzv8H5DJx1SoUwbyAnRWormxZ2nTNg
            o2vU6b+XSlzLmFKfJr/2CApL+EhTPpncYn29nSmgOTw5Ceb6BqZejA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-18T07:48:30Z"
    mac: ENC[AES256_GCM,data:hp3wmBw9mfvUEHcRuIDF6dleYyBoAIDnjgl9/pSsmbgYtux+Qs7q3X+n7boEnsi6aW3KNVbN8dDKWx7EXXK+N+Kb0LOgOxVatQGVLHEVJtiAyf0F/Xs3RbNNptoAOGnXRkG0CrYst9ULWnpbqVOsAyfxjnMiycUphLt1pMMYgd8=,iv:zRiUIkLS8XU/Wgqn3jkntP46YbXFoNRsczqwhcs1Sa0=,tag:itSLjWq+3fGfi3t4AnlJGQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
