# yamllint disable rule:line-length
---
apiVersion: v1
data:
    ghcrPassword: ENC[AES256_GCM,data:Z3mDBIn/sSquzJq61kT7JuuwlLAA+Yfa59ICCoVPo4BbwkSrlWeVQPIghWeFydQqq9/RZFLn/T8=,iv:GKl9NVBXhrTzKrz36unLb2N2ZLgWmdVPdn1s3Xzl+I4=,tag:ECVSzoLExrRxv6T7zuYt5A==,type:str]
    ghcrUsername: ENC[AES256_GCM,data:O0X5CWFygzURvlZnqn6CmcY0jMdSEZXh,iv:wN8DLREQkC5/p4OTqKNvtTksbYVRly10FaPBZkdloM8=,tag:5HhdkH6jQIYkSGe59iSmHA==,type:str]
    installPassword: ENC[AES256_GCM,data:r9ZbS54tVAVSQyh9+ozDXQ==,iv:YmMyaOOqBl2rGftZ35d0bO5j50LscUaCYqbpg8aUFuk=,tag:JO8S/3b2aCswo/KnUeBlPA==,type:str]
    password: ENC[AES256_GCM,data:S3QTZNAxWa8iI5sWFOCEHC2ql9rL1pLrpGLykA==,iv:9r9V99xypc0UzCnIQOCY7MYXQ3GjnSUYOKHX6r2gWcs=,tag:OfsYuX2b+MYAvU90R0Fn9Q==,type:str]
    username: ENC[AES256_GCM,data:Qly4F4oneyw=,iv:WNFh2+wRouQFdhzRiz2X3C9SizNc901su2wTeH0cBd4=,tag:1HtR+TDftYxV7P2XOW/jGQ==,type:str]
kind: Secret
metadata:
    name: harbor-credentials
    namespace: harbor
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzT1M0YURaNHNNL0lSeGFr
            RmVXcGUzc1RRMzJyeU8vU1pqZm4vM1hVelFFCmRTeExYcVUyd1orYUJKdS9sVklP
            MFJ0TmlSUVdNSHJNNmdKaHpMYVY2cU0KLS0tIGxvK1NhUGRuN0Q2NmVVOCtMMm5N
            SlhaY2JQdG9WbkhwRmhZWHI5STNpRzAKxKGo4zR6HAywwl+5uCQxWKFWPpZhduU7
            Q6S65r6nngk7JzJy5F2o5LOnZyw5QV0P6esAAhpUMCxjaOSm2AgyaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-18T18:12:50Z"
    mac: ENC[AES256_GCM,data:aJZUhlJQu0dEPzYWvRRZSRlspD53gVQ99pOtwTG2jI3cAMpXxWVYEibSeCgWPkW3GHZTPFZmPhhqT0XpvJzSd2gAEVOQzd6u3aNhFSCuLTXWHbTpqH8Ny9yfF7LIBhd7Yq9wlt1y/P5gZJWafx6OB+0tiEeqnzVuaixiHNCmKy8=,iv:dLJiNC2cvAXKvzD+QOflgifeMsnypyKvFON2YHoOwm0=,tag:Fd82xqXB4dKTuW2+ykEkkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
