---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-etcd-backup
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "${etcd_backup_sc_name}"
  resources:
    requests:
      storage: 2Gi
