---
# yamllint disable rule:line-length
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-config
data:
  environment: nord-no-krs-1
  base_domain: gcdev.zone
  environment_flag_emoji: "flag-no"
  b2_dataplane_network: 10.24.0.0/16
  b2_service_network: 10.23.0.0/16
  b2_api_vip: 10.24.2.1
  kubedns_service_ip: 10.23.0.10
  elastiflow_service_ip: 10.23.0.20
  pxe_dhcp_service_ip: 10.23.0.30
  evpn_rr1_service_ip: 10.23.0.40
  evpn_rr2_service_ip: 10.23.0.41
  ntp_service_ip: 10.23.0.50
  s3_service_ip: 10.23.0.51
  dns_service_ip: 10.23.0.53
  coredns_reverse_zones: 23.10.in-addr.arpa. 22.10.in-addr.arpa.
  public_dns_service_ip: 10.23.0.6X  # X gets expanded to 0/1/2 for anycast/primary/secondary
  public_internet_range: 147.189.200.128/25, 147.189.201.0/24, 147.189.202.0/23
  instance_host_router_range: "2a09:7000:14:1::/64"
  number_of_core_router_pods: "3"
  core_router_edge_a_link: enp193s0f0np0
  core_router_edge_b_link: enp193s0f1np1
  core_router_edge_a_ipv4: 147.189.200.2/28 147.189.200.3/28 147.189.200.4/28
  core_router_edge_b_ipv4: 147.189.200.18/28 147.189.200.19/28 147.189.200.20/28
  core_router_vipv4: 147.189.200.129/25 147.189.200.130/25 147.189.200.131/25 147.189.201.1/24 147.189.201.2/24 147.189.201.3/24 147.189.202.1/23 147.189.202.2/23 147.189.202.3/23
  core_router_edge_a_ipv6: 2a09:7000:0:1::2/64 2a09:7000:0:1::3/64 2a09:7000:0:1::4/64
  core_router_edge_b_ipv6: 2a09:7000:0:2::2/64 2a09:7000:0:2::3/64 2a09:7000:0:2::4/64
  core_router_vipv6: 2a09:7000:14:0::1/64 2a09:7000:14:0::2/64 2a09:7000:14:0::3/64
  core_router_fixed_ipv6: 2a09:7000:14:0::4/64 2a09:7000:14:0::5/64 2a09:7000:14:0::6/64
  core_router_edge_peers_ipv4: 147.189.200.1 147.189.200.17
  core_router_edge_peers_ipv6: 2a09:7000:0:1::1 2a09:7000:0:2::1
  core_router_anycast_ipv4: 147.189.200.32, 147.189.200.33, 147.189.200.34
  core_router_node_flow_ip1: 147.189.200.129/32
  core_router_node_flow_ip2: 147.189.200.130/32
  core_router_node_flow_ip3: 147.189.200.131/32
  akvorado_pvc_size: 40Gi
  service_anycast_ipv4: 147.189.200.32  # first IP from core_router_anycast_ipv4
  ingress_anycast_ipv4: 147.189.200.33, 147.189.200.34  # last two IPs from core_router_anycast_ipv4
  ingress_http_private: 10.23.0.7X  # X gets expanded later
  ingress_private: 10.24.2.1
  ingress_public: 147.189.200.254
  ignition_server: "10.24.2.1:32266"
  join_token_server: "10.24.2.1:31385"
  ceph_pool_ssd: ssd-volume-data
  ceph_pool_ssd_data: ssd-volume
  ceph_pool_ssd_cluster: ca070759-bb20-4b52-a5af-f0997eeaa10a
  ceph_pool_hdd: hdd-volume-data
  ceph_pool_hdd_data: hdd-volume
  ceph_pool_hdd_cluster: ca070759-bb20-4b52-a5af-f0997eeaa10a
  ceph_pool_ssd2: ssd-volume-data
  ceph_pool_ssd2_data: ssd-volume
  ceph_pool_ssd2_cluster: ca070759-bb20-4b52-a5af-f0997eeaa10a
  ceph_clusters_additional_fsids: 1b659f38-3f6d-4f85-8ca1-d9f378c1bf82
  ceph_monitoring_endpoints: '{ip: 10.26.105.190}'
  etcd_certs_location: /etc/kubernetes/pki/etcd
  etcd_backup_sc_name: "replicated2"
  rook_ceph_nodes: '[{name: gc258-ctrlv2-control-plane}, {name: gc259-ctrlv2-control-plane}, {name: gc260-ctrlv2-control-plane}, {name: gc261-ctrlv2-control-plane}, {name: gc262-ctrlv2-control-plane}]'
  e2e_tests_cron_inst_susp: '"false"'
  e2e_tests_cron_sg_susp: '"false"'
  e2e_tests_cron_vol_susp: '"false"'
  placement_options: '''''''["A","B","to-be-tested"]'''''''  # so it makes it successfully through all layers
  infradev_librenms_ip: 10.24.9.18
  infradev_flowmon_ip: 10.24.9.21
  vast_api_ip: 10.24.10.20
  filesystem_operator_replicas: "1"
  rdma_network_operator_replicas: "1"
  ufm_address: 10.24.9.4
  public_dns_zones: instance.nord-no-krs-1.genesiscloudusercontent.com. 200.189.147.in-addr.arpa. 201.189.147.in-addr.arpa. 202.189.147.in-addr.arpa. 0.0.0.7.9.0.a.2.ip6.arpa. nord-no-krs-1.gciprd.com.
  prometheus_size: 1000Gi
  akvorado_service_ip: 10.23.0.81
---
apiVersion: v1
kind: Namespace
metadata:
  name: e2e-tests
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeadm-config
  namespace: kube-system
data:
  ClusterConfiguration: |
    apiVersion: kubeadm.k8s.io/v1beta3
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        authorization-mode: Node,RBAC
        feature-gates: APIServerTracing=true
        tracing-config-file: /cfg/apiserver-tracing.yaml
      extraVolumes:
        - name: tracingcfg
          hostPath: /opt/apiserver-tracing.yaml
          mountPath: /cfg/apiserver-tracing.yaml
          readOnly: true
          pathType: File
      timeoutForControlPlane: 4m0s
    certificatesDir: /etc/kubernetes/pki
    clusterName: kubernetes
    controlPlaneEndpoint: 10.24.2.1:443
    controllerManager:
      extraArgs:
        bind-address: 0.0.0.0
      extraVolumes:
        - name: flexvolume-dir
          hostPath: /opt/kubernetes/kubelet-plugins/volume/exec
          mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
          pathType: DirectoryOrCreate
    dns: {}
    etcd:
      local:
        dataDir: /var/lib/etcd
        extraArgs:
          listen-metrics-urls: http://0.0.0.0:2381
          auto-compaction-mode: periodic
          auto-compaction-retention: 15m
    imageRepository: registry.k8s.io
    kubernetesVersion: v1.29.8
    networking:
      dnsDomain: cluster.local
      podSubnet: 10.22.0.0/16
      serviceSubnet: 10.23.0.0/16
    scheduler:
      extraArgs:
        bind-address: 0.0.0.0
        config: /cfg/schedulerconfig.yaml
      extraVolumes:
        - name: cfg
          hostPath: /opt/schedulerconfig.yaml
          mountPath: /cfg/schedulerconfig.yaml
          readOnly: true
          pathType: File
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: instance-specs
  namespace: e2e-tests
data:
  LOG_LEVEL: INFO
  cpu_nr: "4"
  ram_gb: "12"
  accel_type: nvidia.com/rtx-3080-lhr
