---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-temp-ceph-access
  namespace: customer-operators
spec:
  selector: app in {'customer-volume-operator', 'volume-data-service', 'customer-volume-downloader'}
  types:
    - Egress
  egress:
    - action: Allow
      destination:
        namespaceSelector: has(projectcalico.org/name) && projectcalico.org/name == "rook-ceph"
        ports:
          - 3300
          - 6789
          - 6800:7300
      protocol: TCP
      source: {}
