---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vast-collection
  namespace: flux-system
spec:
  interval: 60m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./collections/vast
  prune: false
  wait: true
  timeout: 10m0s
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: ConfigMap
        name: version-registry
        optional: true
      - kind: ConfigMap
        name: grafana-configuration
        optional: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
