# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: rados-gateway-ceph
    namespace: rados-gateway
type: Opaque
data:
    ceph.conf: ENC[AES256_GCM,data:zH0DFHbMXX6i/CaBGD6RKVvKM4Lgz6FJdhKv/Y7H3mVrKp7Cmk//kl2Odya4cjy7CCCmGaqYJoeV5F1COlNd+4LyEP5csMAfiIzoYUhYDUn/dozHaApz7LX39Zf1STV+uYWwx/7gp1MYivxC+6RCJIGZuIGcRkihJ3n9/HRSFlGrQ+2uZQ1CTPKo2y/X6HfHdy6dIN0ca+XsIcUwIWPe7GRKPOSmmCxZ37p7XSfGPGPB1L4g51hxBKiN1tQA3AQxSym3YbOaWYPdA8kvbkvghN0Wr87WmtdnjjxA7Vnc8+CWgI2KOQZ7BJDPmLgjX36odWllyLGhudqok4ORNxoHYDNZdP/uJ/IOETvhFSKAooLKHY3/MC+ULXxbSGl3dA2/CMXxjcFMatMvlhwgPgWPKramcXow+uvkhSQuhkSyGlZi2fD6HXilgf0/EMTXQYrA3eFYV1JyHJ0T4Z8ruyygpPJ7shisQa5kSEjfDLs+TFAEPCgcmOnoX8mhec4=,iv:99AA8IE93GoiNGku2jKOcp5Ml+R8ctV3jqEy2n/zk9M=,tag:ucim9Rlfu4HkBHbdQfSU5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYi9zME5mdWFyUGU0YWJy
            bjF0RHF2a2xpbDU5c0hLemhiV0dmTFdES2lFCkVRdkphNjhuQkRoOGRlOGlrZkNN
            Y1FYUlJyS1BGSWREVWxLOHpJNlZvRncKLS0tIC9NcjRuV2hsN0c5eGhiTHk0dlNj
            Z1NqdkFtVFVLWjdzV3hTdFZwQ2FsaTAK7SwVn0tOEddzUWKzis+shNQca1BBWt2L
            Hpem4lDjxJGzUmUa5+51OUeEPFbAJEJwy+8dR1xXTWcfb9E06sK8sA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-25T12:28:16Z"
    mac: ENC[AES256_GCM,data:B8QdHAFdFs57F/w22tC1TokYqqdUeUPVrra2ayCcdEGnRzaKUTN1hcqSvq04opiXGDZKmcyXGoQcGe3bYGmZttwnw4oKvvU4K4fZ/c+XWKcZbKCXf47m3pxSxpZw78vXUgoVXhmMcSegrNCI2iC2irFq9Sb76rzys3Xqpfs9mXc=,iv:tKlaQE56eGeF4tsYQRpDE0d0kOkJEDq/Y2Wk+vzB5r8=,tag:po7Fqbb/7KuMCdBzsdfR1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
