# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: customer-volume-ceph
    namespace: customer-operators
type: Opaque
data:
    69f4ca1f-443b-4023-a9f0-282ea9765ef5.conf: ENC[AES256_GCM,data:/ksl/4MzpIliMdeCGfyS6rF9pzksueb/sHY2vJsp4L4B85YSTF2nP6KapoCne8fdsw3wdMX+07nsBjUjOVCO/+wsilN9oseEJhtslFD4GsP23jRBehTKMOSvAfGNVHCQgMXKlTljSNEc5qVY2pON05B9igXbsEp2Au/331rZ6DMTzOry/XEcCSDV8Swnx7hee/kNUsarSmDTFMl1j78i09OV0GyZi/07glji20ALLjqnTYqFY3mhxEOaemLLEBaRLIvVmBhHlLxh1kShdMSQFBxxrY9SlwlqUHanaftzOlACM/ld4pLIKc0iUZI6vw4RVLO8GXrce+NI8riNrE7paL6Mo0haUsSxlIcM0v2Gg6Sds3Yjt5k26f2dJVYk32WcTDtc8RwbCejknGo0wFyqS/gcooGmHV+5Z1ZRRofgrnnwlfGX744XoFrHkj73IeFZMc4xEfkxDp2YQCSeJA7aCVGRk/MSZFem3/d1grEBmh2Y4FCsPuNRIW5J9uQ+wJC1,iv:uMocaJlNZG6R45AWY59t2DbuOVbDY1pKNJbNTRN/Nfw=,tag:6l7mhEt+EJIun44/Bl/p4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNkRxMXVpNWlzWjFhTDdF
            Mk1SdWJYN2pMOElnVVpZUk9tRHd5Y3ZSa0g4Cno2em9KUXhNWHVyOGZlekF1Y1E3
            MmVIekgxQ0luTzdpbWhKUS9BU0F4azQKLS0tIFhUNG52TGp0R3lRRTdCa0xpazU3
            bDluOVYyUFMwbGk0bHlXblFTUmRkRjgKX0pqCjH8ZbfRSk5HdfY4BlEXc/zIJ1oI
            E7O+7ldPl9CXcTYnur0glEHP7X27ifGTD27VyOkzUgrXO5cETgZQkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-25T12:31:00Z"
    mac: ENC[AES256_GCM,data:FtjEw5Gv77hn/V9BDz57yEeZQs6VvUVonhqFSrqhWywrWepRyHLvzBMxbiEa7CBzzNQmZ7F4zer6tP2Y2fCgbUdZXGaYo8LBBBwiyS1cuMZ3H0+rWOOviAClt2oq+4I+4LM8lg48wC46ZRdq6kV+7LNlVJG/w7PLRhgofBYIQus=,iv:ZyvyzH34LfGxHL1GAmGcLrxsG2ELjsU5toaEh1eUYTA=,tag:1gxtckQSm9ta+/W8w8YCKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
