# yamllint disable rule:line-length
apiVersion: v1
data:
    auth: ENC[AES256_GCM,data:sLINie63b+8WXFc6IJ46hEdCAM3tu3U9ZWCij8EC1bJZWaXqX1rVBgwyJpJfUMedPEKFjJhQFHA=,iv:HQRuQSMHqOYTsH1NcWDG6PyzIM8CEHuGM5hGy5pBLXs=,tag:Qvve5uQxSS6nQEjbDFUaVA==,type:str]
kind: Secret
metadata:
    name: northbound-api-credentials
    namespace: northbound-api
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZEJwZk1mMnY5UG1XcWtH
            RlVZbnFFMG1aU1lNeE9kY1o4WGNld0ZvS3lzCllJMC9rRUI2aVF1OW5mcUNrZmE4
            Rjh5MlBuUnB1Q1pOdFp5Mkh6LzdvaDgKLS0tIDlpaFVxWkczaVBSWHp3QVVYSVZT
            L3N5VTU1YnJCdEZ4ZFRMc2JJMWhTL2MK2mEyXumW2v8T42Ptg/ZKdTdSgtvqB0dJ
            FKCZ3ARvgJHIkvdJIMiIzyxsYlQedjfyGfAfpuvLKPEcm46cV/YotQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-10T14:20:01Z"
    mac: ENC[AES256_GCM,data:SpiixvmTL8VCj66xFujEUTqwS3ejuDfe8ZrAbwTg6ucHqAvModv2IeHXoJP2UJVjBaFnqhnFX4sXCyGGcbln29XN5+hodsFFEumCh2+KXiAy0guq2rGCHg3v/xu9jJU3XQMx25Efgn4tHBKR1H+UNyUHfhMuDqYEfr7OiDh6b/s=,iv:SeFJjcuy1ooVNWr5RwHVBnBP1cWPbarXAqgRXZEOP34=,tag:LI1Xk56Y+NCZ4ieaglXfJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
