---
# yamllint disable rule:line-length
apiVersion: v1
data:
    auth: ENC[AES256_GCM,data:g2GCL8mJQfXz58IcHbLIqAM3BfBBhj/uogIGGhDqZhyT1VlESLw2kVmtvIXK1uSDdYGzsg==,iv:9RqfplYnsoqJZOpP9PymVHxBl4R4hNOMngYK8/sMFKA=,tag:azZvucwqQU71CxtlxHI8vg==,type:str]
kind: Secret
metadata:
    name: prometheus-basicauth-credentials
    namespace: prometheus
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNll6V3RHYTVBbUVFSnJq
            VUFnQTlBdlBZNmRhMTh6MTgraS95ZkozTHlJCmc5MW5sV2pTYXZQc2dzZGZhRndJ
            YWk2emdTSk5uNWMvSm40ZEEwUk1CeHcKLS0tIHNqa0NWRHl0bUc4NGRibVlMNzhT
            NFptcUpTSTdBQStrZURMbUMydjBNVDgKm/dLH0macKer+cNkM9erLpatAlEACtlN
            EA7DGJZDpRiz03UjZrDIm4pE82n6XI/F1L1TggrIhfMUq2vrKTdFqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-06T14:23:35Z"
    mac: ENC[AES256_GCM,data:5grkTCkPGINs+c0XA+R7KWrIMx005uFPc1+q0HTS6xfayxBnfD5R3iv9LOVHtHYHo3PQDrpvJCcANL5BcGYQ39UB9jMY3u9y2ckx9ZVeByyqLSid5plMNLYxpNZaIPFAAN94VDU3YAlPD3vFQmOe2+DoXNCtWZZlzmEFaAAv+AQ=,iv:gnqIBNSj1P2kCiQhqAi1UcWLVXi3/NOkUqjT0k+DPO8=,tag:IuUOyGh8KUisj+D5lmJ+7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-slack-api-url
    namespace: prometheus
type: Opaque
data:
    backend-v2-notifications.txt: ENC[AES256_GCM,data:s8H78ufOibwu8yOi+4W/KpaO6Gw9T3KHcEAw2mIT/MJYgRf+Fcr0eU5y/TV0q31SB/qv9Dxw3bYWIu7kCPebUB+RluJA+OKUp5SDY2FannSYD9xujkjegM4N2F9s2vrYa9CQANpF3Eon+tiw,iv:fEtteB7anorr50L4u/JMHZSizW1iprbCWDIZd78aPdw=,tag:G3qpKbR7R0RQJcJRWfhX+w==,type:str]
    gws-b2-cleanup-notifications.txt: ENC[AES256_GCM,data:DIZPeTEzsxyl+DTmcCC2MjGEEZ3O45HEUTbwgmx3pTq5Q7clcZT5Mf7X68i3dBdc687HFrTGO1ROagt2KjMtT09QHkM7qWut9cjNTfi7CIJJeU0rhtokxXdrHv0jWA2qxdpEIMueTakmPGUe,iv:PB7EsmlDomvxrwsacBw00F+ILL1/dokmSvcpvykFX4s=,tag:aQQqaBaOzjFnEXRFxLvEKw==,type:str]
    rook-ceph-alerts.txt: ENC[AES256_GCM,data:jZ1/PkbbELPTTb5hCBbyBaEDIQChp6tvwoUr/pcY6rU+3mkYXcWw9lA9QhLkpzNmMass2z1B9NeyKSUu1uZRAy6XF47Us6DrsP00X+czh6/c9Efoa2a1nqja77obWBKr/BnOfxZFzHU0Hia1,iv:Mu8Z2feZP5prZASkqjuTFjG73gqzJGqZu7npPtzds/o=,tag:xez/MDBBMxER21YiO0E1jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMS1RjR3dqVk14TFBVQlBr
            Y1JscVNNeE5KSzN5OStUbml1SjgxQ1c5cjNzClVkVVRXL0d4RGhpSTYxdkZxL1Iy
            ZFp5UTEwME9GYmpsREVCRE90cEZwT2cKLS0tIFNJSDdIN21YcmxYWXk4clZ6TFdF
            YU15VU9ZK1ZybXduREduSkRkOFFhK28KbV7bAepFMqihlw5zueaGgQZCrVsPgQd3
            qvsL0GBUhmsbc4ZjLy0Mugbmy9Qppb6tnShqmrO3amaIjcPoC2vWCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-06T15:23:36Z"
    mac: ENC[AES256_GCM,data:Kd7rnaUGq/Tv9wctuu7ySU+a3YwHQ0Z0YRWg3pJLX9YTGzS8XWjZANejfg7DiRkkQSxgeLwg1ApdGgDWANxH49tSnnmnfhc9NWgJCqYojbUJTZbCTrX4vNtWBJrYCELwRR9GkIGCYZLINSFTugOuEChQ8X2YqLmrjEQUe3pXA/w=,iv:KDFWOc7dDcCwRSk/C+ST140GDp6YX36aTtFvIp1SRvs=,tag:yzkOCuz0WZ1yQrP61u2cxg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
