apiVersion: v1
kind: Secret
metadata:
    name: snapshot-presigned-key
    namespace: customer-operators
type: Opaque
data:
    key: ENC[AES256_GCM,data:FBloSUz92sJ0JPwBGcxOZIoeDY69iHGmvGmn0y9I1v348rxTRpmIkN2Zq5mcHL+vru+phGVUvMH+546dbx42cAYGjG8ZoiN2/eI1p1VXsM7GRpbipZTuRUg1qsVKG/f3qovAjxoCfdtBDNMM33UlnIKm0INAvNlbK24rGCnHT1rQFMOgpcLV8LneBQNWJWjv5tWhXZphwrfwlbbog7/iyxUtgdUXHjKT+vPyuWE65b7Dezf6acX1aRr2Tq+lH3BY5uKCprJepfOUSz7XgsdVXWB3qvuDiPpLWjVUoTFMV4iKnam9ovN69rXoqaZC2iVETmWgx52ZTcOwOWWc5qlPhLTRk3KdtjAfHOdJ6ZtwNHDzuLr0wKsTxthGZ4i0CIUIsNApHwUancTXQa9pQlh11HDEjC2nNMgKzi31r5kqoWTnfNJ153AjpGxre0koBX5T,iv:pvS57X1UvnZp/90TMl1GbNj9r76QDjSZGbO7o4SkOLo=,tag:NMhJEz/qCrB0Bjs2ogtzGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcHQxOENVdHNmanBpWHBS
            NjRIT1gzMURYSWVYMzQ4UU9zNHFiVkR1Q0Y4ClFUTFAwVHRWMlhZeWRRTVFnMGRv
            Uno0eDZNdDlJWWh4bUNmUnEzcDRJb2cKLS0tIGpkejJIVkY4cVRySllnOURpc3Bs
            OXdLODZuVFp6TElHTkFIOEI0UmtTMjgKEx4YIBhB0LvWWBtAAYMyQX2EBR249tz3
            eQSaE60DB81IO0h1Nd+oosz+2vWcVB9b0xXTCeR3fKBJ49hoSSxLKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-06T09:08:47Z"
    mac: ENC[AES256_GCM,data:mty+2kGwxR7gkbkpQCsRgUZWnMSRPBIaTpEExYWzy4z9sPhE20lHaYUphpKMPap8s9KBOoVXkw8b7rHT3coJspcugPd+HzHMRh26ByaPB1glRiyPdBwWLCztYXonOOgY+fKrF03sw3UDVJVcc5V39fGacfE+23eJpuUIuSbcIBw=,iv:vnF+5vvi0U6Y0xNn2gtoC8K2RFCHcwtqhY2Q74IgcrA=,tag:d9jq591xHqc8q2LqflmOrA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
