---
# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: rados-gateway-ceph
    namespace: rados-gateway
type: Opaque
data:
    ceph.conf: ENC[AES256_GCM,data:gDQyHn+zYBOOX2eR9Ialeb+IcWgh3UI4zkKLy9Pq7Ud2xCvjU1IRo96LgWr9dTvf7qvpSILE+NZhwWnNNzh/Ta9S4qwQ8YGK4WvXls9izGw1eLb8tWgtwQg2B0UWcU9NNWa6LTuyNkR2rQfCKMQl7//fz11qQP6kZcsW7Jb+HEmFykbWmh+0CRptDGC4d/XvllTOuPJ49xxcE3Sj2YscTzR7FY1aRXJMtXRsqW5tNwIrgZattOVunT/59eH2TIRLDGzNO4C2rqYmwZ1O6AHxHFt8kRNYChHgWtg9nz7+szVywn5uPJoundvca3HZd11cMIYs3NZdFqncqBlKOGL1N3NxeCG15A4QnwNw+rBJfLf+hGDD653RVl/X/74g5i/XA4/77+S6wLZlGF03kHLJMZldNXZXU4NFD5UTmz8H9i0p4Pfx6oe27eEupCUXP5QOpcQX8JbLsb7ChSTrCtbZkbWYle6rfgmtqLCsH2luDMYNBpTSyxFsJmy3/xsdo2QlP91V94IFr8BVHUunRuG9VtQLyn/Oobg6O4OcC8qfGcs1ykXj7OHU6TYaRDLkCqdgro1nMiw+JcwNWefDokJcypHWKyM0oUUWa6QsmMekTkkIM7MvaByF,iv:fgWIF5shNAInOI/U4b3WKGiQ5Lja3MONE83dCG+zW5M=,tag:rLQ1yS4pvol/bZlG5zau9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTGpHekhReXJJdU91bFBo
            ZGptTDl4YmpWVUxuTFQ2Vnk4aWxUVFRlMGdnCmJsTEVobjJJRVhWK2xUZ293VHB3
            cDlJSS9LZk03Z0hmNFFkMEJHRWJpeE0KLS0tIDFYbkxNOUw5RGZDOVkwQ3UwYlJE
            QUQwNVkyR1Axc005aTFJVktoYjBjVVEK2Zu8yYTly8NqRoX8B43SEA+JIiTbLx5S
            EULh6yxtcExLCA9BrlKYGRedkmr4Nqxsk5E9j30tWw12JJLBMXpnpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-11T08:32:35Z"
    mac: ENC[AES256_GCM,data:o+BWHoA5MsMWvcvYXDWRoGH8xbZ5Nnzf1hDEvfJvJn5Iv4Ns36Rg7rzQnaqukLKt50YscsxDwAGIueU8IqvyhUqA1rqO4GVaYOqdP7ws2JRhxHDk6kXifjs1X1QpjZehVp4kbDhWjXZ8dIlryNulmmRbyTbfpBSTXfGrJAjav3s=,iv:l8zc/CGXFyApSdJY+6DQXgwGjmSWlNb/3FNGuMczeeg=,tag:ZZeBbbMc+9NTs2FusOvMYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
