# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: customer-volume-ceph
    namespace: customer-operators
type: Opaque
data:
    1b659f38-3f6d-4f85-8ca1-d9f378c1bf82.conf: ENC[AES256_GCM,data:5bNcyOy95VGhGDl0zi6dJPgdEVzJicvdvGnCWWdU2P2usIu7yqP/3m/Rm5EGi87MBfEWtjqcUZuVD7iYOyyBkfjBwPmjE2Drt7nsGOSRswiu62qhGakmUd+lov7OD/Nq0zFT0nNd6adxg65qFmSUOfRI3znimp1+Uq0ywtNJg7AeKFxfsoB2rmVYIsixikXnXdXgUNxAJCHy40MCESLmS8QKzrvrh0VibIDUhg4ruNX5IW4u5UzXL2klDDluwGKi7uNQlmYu1EwB+0eeaZM671ZNgrBL4Ey2DKpIHTtPHIliuchkwmDIADGcK79nzjNjhbQdxL2e8qYV/VzTjSJ2eszbAwMzKG/h97Q99VI3o52gf+3UIgjBDiPWZvaSxcSMgtiq+lqFFfpTjEFm7udYGfi0bnmkDWfWcC93JK9JqM6iIvWYCIYR6uUG4se9aVT78bizp6Szx+RsdxrcYJcYWaRJsPSYAAppQGiX7rcQmrMOTB/QG2jrDGGslLCqDs1n1iLuJA==,iv:mGZX9FWcHHiNr2CQ3tga20RvBjfUnBr/QR2yx43To34=,tag:1iEQBTLMMkuYTSeVe920EQ==,type:str]
    ca070759-bb20-4b52-a5af-f0997eeaa10a.conf: ENC[AES256_GCM,data:mXRHmCxTZkQhx/CxYO3rE4nP61IAmIlXdQX+KD52YRy2deSgTFo48VIKFh59mzNKCb7HMe+6M1A1ixskfqxGveiDrNjscenV5j0oO3a6dfFYaoDF32dOT1ZXBTqUZBa0nE2owht50fM+9wWNUsqJsu597coK1FzAjaWUD7JenviSMhDdy/CgVwDK8ONhSsz2sNj5d8tB3T/x51gfbnLSXgYu5ixDKdJgZwAtnAlhroKCGmnMzWpNXOt+sVLxU9/B99Vq7mXe7br0KRhoWPpaOnoobwGoWTBuOrQ4fs5FBtW0Dx8+kGmEj6w4NSFop3NOJcES45i1TnJ0+bf81D/Axp8G4cbXsVpXgtg+Eft7LebGdqZcVWCOlSMvyItTudDXccCvodnmXVbN95ItklVYx49c8Qprrp5aI/+FJbwMBbzqehZXDsJZxGyhDUjMzz9E9l920DqtCrGfJxi1O8Sjtb7M8GFsJ1V86pfSo7ATPSrnDX6NMkAkr5GMCvd42nQ8/1nlrpdkyHovQETKRjs11CV8iNXNlNuQyUEt8DaE+5Cjt22h1Y7Kav+11nqFF/vvXuy4ntM1r6LllFitO6m6SbqYz43HLPHEKStxkIfl0qJZTGJu6wknvdQUqDhTf+BJspm6FfOq+y2l4nNDwOfDjjmIHcmi7BX7NfG3HpirEPVxGzu98kUXe7GdHvzS9xcQL9POzuKMz3mrJk9icwxM9xjSOE/HQ/Sa5J1cGo8mvLhqTfQf8zBJSFbssjB/rOknDow3c7kH70LzcmSpRpHXTCOQYki9S9ZhcP9bXKMfdoOd3bFVFa1Ye+dzEsu4bANNQ7+depuhvkPFoRzCG/Qvyb5Oq2Q8KewgONKxAA==,iv:U0Wph2JhKNwTWckFqIcP3/mLJ+cygmOeG4uBtyhzFHQ=,tag:+Y8AwnfEYdU4bkjG/F6sDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMGNNK2NGQmEveUFjUmtx
            QUJSUU5vV3UrdG5VVWdKTXF3Rkowc0lnQkhZCnMwV2ZxRzFkT0h4eENWZm9rdWtC
            eHN3TVdQMlJvUHhxNTVPZ0JMb01YalkKLS0tIDNveVBGaDJ3eFRjRzhGUTh3dWt3
            eHdvakk3WVpBU3J4RnFreWprNTF1MXcKJtie8qNePWvA14mmdU1rlX6VfaS6uAz7
            12Tbu2gFbFrBQ/Wo0m4eP4eKAJKwL4rSpRxBVdi+0s6C22zn9jxShQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-27T12:08:43Z"
    mac: ENC[AES256_GCM,data:5Oyyp32OSItGSJCfTcZS5lEABpPL2dSC/ty0D5O7VEnGACIeZq7/fDJ6Dhbm+AT0vWvwuMro9+YpJbL5e9jRRaKX1JMFwERqYwt7SVS+sg6vG9QfdNtql0NNCBz1vBF74g5J/YZRvCuwpp3dV5ld1CSsGvC0OmSchi1YLIGsqik=,iv:voY02lXHsduewumeiPvs70H2bzJq2DxcMOxJiNy5+0U=,tag:+UpE4B6qesISUGFYnPnzyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
