---
# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: netbox-key
    namespace: infra
type: Opaque
data:
    userName: ENC[AES256_GCM,data:+E/HGSGjxla9Ja3zbq3OCg==,iv:4hOF5famhJ6p4SQ8OR7m3YiR9SVG9NueYLqR4rl+Npg=,tag:Eyuu60epDK9Bew7FUBiG7A==,type:str]
    hostName: ENC[AES256_GCM,data:MaJBdET10EtUbud3aRTa+A==,iv:riPUexPDZ3kkpe3aI4l1VHgnUfkf4MJF9edqT8YyOQ4=,tag:ev0d9j6VR1kWCQZVotyIJA==,type:str]
    sshKey: ENC[AES256_GCM,data:EenXsHwpoQCAIaB2NlaTH2VJEAnsvfnNvpoMgtn2VJlEaJXdIJNha0b94OP3teiuZg53YrB9O1Yuagkx6Nu52HR/ikuHTEoc6p5QQSCnBjoF95B6zgxE7WbpduWQ/8YYp2VB66DMmf7cuUOn+UqHdyFCehoksyOmRu+iGo/MtF83F6iwk3MqVP3HIPhtm/FBlH9JIyQe7588GahOIpdIwHxRqc6cN/2djx0XJvsqZ6dKL07ve6UK21+tfBQfZ6m2YEHuRsuWMblTcSuxikm8rcZTqyKdnDQrnpOnfvPhXnIGqO2mLETYNpWLPJ3ecp3UwxAhPQOpuhnsLP0Zl/bG1Cdwend194/TNoRtMpDWyuPxAkHwYRg9GTRn3sQDHbv16i1m95aka7BDH9DInZKyXTy73gwpqu4kQi0hp2lI/C1xE+y9Ba2Y2cEajR7UNrCj6gszZ0WQlukQrxwUhRllCnfw5e4nYGYuAO5IzNBaFbyyrvcR7pyvtUw4FyA7i43c7So60HjpgmGhnp7XcmpB42wrI1a76VrgFWO8SkbaPMFjFyRw2SN6Jt627myBo6kK460V6T/ucI1bLzjnsP8wXeQovB/36h1UejTktVYbbjKzNZ/usV6X4m8f6Szx8ClMAWGfLwL7s+e5aEldkHPsuyz7eSQ7v+qyciV59Cte5ezfTfjmbixIe+HM5pm50ecXce/sHZaxvzd8a7OCovdvq852O84=,iv:Fu3XB+HAfZ7+UD2rflBDhXvVWk2+OkL8GRSFcJJVP90=,tag:xQsfBqxKJ39LFTNNbNCZHA==,type:str]
    netboxToken: ENC[AES256_GCM,data:7Ax5cPe5HLYS4P1a8yqQxSU7yBtJhv9QpN5jHpRJlXYUqcCi5PEUKEqVAFWmd2y9kNLEU2u7qnk=,iv:tYcUTfZGRR4sjoEtnF+K+Ew9kuueQ9iRA7EiBxcUBAg=,tag:4cf1i1wC+9/SJ2ArV9HJlQ==,type:str]
    netboxSite: ENC[AES256_GCM,data:urf7/HB8TxZ5smp5OsAEqnRKUyo=,iv:pX1eZVhOnxKGtshgpXfSFjk6WgnVcFpI8wOjfXe4e3I=,tag:73PRwAxtyrwHtfcnICcYvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEV1hqek1uYWlVd2xMOXZ6
            bzJPTi94ZDdCQmRLNlQweWw3bGJ2M216OGhnCjRaT2lDVkZleGFTOTcxNnBFUTBt
            cVRRR1BZSWtZS1hXTGo3ZDgxZXlXaDQKLS0tIEtlcGlNYWczMlFFcVhWWi9CbkFi
            TVVkam9BWlhWeUxMM2JsakxTMGowMmcKBiV92qBb6atQoJoTO6kFM2MupsEIfX5H
            in33nNtOt0kQqiPZAwEMdPGV6jpj5osJ1CZ0aCKv7HpWoehmz9NlYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-24T21:49:25Z"
    mac: ENC[AES256_GCM,data:0KT6TSStXvYXtwS3uXKsCGQQuSuYI+P2uDu89FwJwvTh74iSLV9RhusO0cWCjPd7PNjPhJpPCS/bJPIArptBXjXdmlu67jqf4ilqhxbi7erU1Rw1WqournSzTT3JbYdVM0f8j7kQYIOsu4lhR/ZtTcOdltifU8HbAA6QhqiAIM0=,iv:hN1/O24zxWLAFaocGby39/DeGcFkWDVeqBXjMefjHbU=,tag:Ez/b5O17z7BtG+D/8jYFVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: netbox-key
    namespace: noc
type: Opaque
data:
    userName: ENC[AES256_GCM,data:hUGY7HAXNcA7rTbveRmSoQ==,iv:9JA5IT5fApiTEYmxCPLOyAPvQZDPs0zp4+C0k6GEoew=,tag:e58+298t1xwPnV4mstTxaQ==,type:str]
    hostName: ENC[AES256_GCM,data:y92RmBfMgyfVseS1yJNI0Q==,iv:WFysSCz7XhAHOcDnjwbAblvOFBEbLmQPDgYuZcqJs78=,tag:Ig9yyMX3nngWYzqyeG+SMw==,type:str]
    sshKey: ENC[AES256_GCM,data:4bHoS17XUqCjejXFV0sX6V/KY7c+2kGZ7z7/Gdh1BOklBO84REjcO7kUftXBfMsSfOBTcrKo2aWX1JW/6jdfkwMCnVm9NHIAJziyh48zh+ZyrMA5SMrLQO6pzh1xhORmoW9b66KcBSKC6PAITyOk8TpEJQoIO5+w9A29Ne7Cslouc+cN1/dAd4D16AF/3f7L8rxkSaVh4H5ltYOM+YRbP3AGJrSz085SzAC6hQ/NSR1k3TSy4Oe8JGts2JORBzInDByU2Lbvpid2dHQe/9Y2T278eki5NnxvdPRWm3M+ijLRPJIWcYC4WDff1Aox+JPh717w9ySwQ5EHdBHzMkHAqL4TDhO7uxTh4LxWJ3yV44po7PsuZBOtq0m+HhHkJNg0/x4kZfpNWik7aDOHDRGqB2oRZGZjqS/oYoToGIXjNavOCyzFrREv2r/+FgRUoJN/6CMv6VSSnms/+jkOs829C7UaSCnVfcNkP4205B7Yhsj1/USutcXrihatbBRuOxiWSJi760DYkfzO37roV+c2n5zy/4SaPUhpTlgvg5K7AavGvoV2gxbiuGsvOvO45G+75aPcWpIqSQrLcYvS6fcbBE7cQJICkQ/nWPK2GyUFdqm5urtzdTPB15F2VkhQgCdVAj22dkCcGeCUejdlGhjOjGXdH7j1BDGzJXANW5lJqqh2U9d2XrWc70lN6vGVL7HuGjsdFjEhxI9TVAjBwPhb+fVOv6Q=,iv:GHL/WYM3Bx6QLbDKuyUm6EfnuFBRM1LWl3rzHk+ybZs=,tag:lfGIjKZIP3w3imlGIXAPUg==,type:str]
    netboxToken: ENC[AES256_GCM,data:p6v9LKb5iVtuFunfVQlxU5OWIbJmY9932NyObJPNkeu1wo9jWgaLRErm223kfm+V2OIulPJ0AtE=,iv:RExjlsWoVSH4e7PS0ccEkcYiyNEXUDnBJvDCSn7MhKw=,tag:RSDdCRXGRqZ1J0WX6dzo/A==,type:str]
    netboxSite: ENC[AES256_GCM,data:KES0O68PyaBkS+tx2guZFQpPVNY=,iv:a6XZnqE2zSVf5L2gMwjd+/EaOkIFQI6nGRyT3AXZ3dg=,tag:IBUnor1ML+56yAWswfPMmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWjk1UzJ6MzBsVlNnd3B0
            QUx0ZWEyMGdKSlBvZUVGSDBUQ2dFS2QwcGhVCmNpNzJ2WmRRRzBTQlVveFp3R09s
            OVlwMjBaUWIyZkdWNXkzSmNmMnUzN00KLS0tIGdlVFBsVWgxS3FzeWZLQkdxUlE4
            WGFEOHo0MnNjQlllYkNMUEdvVC8rbGMKDwm7RcWgN4QEJcfhXK7klqKfUhN6CIqk
            rUqOJeZZF7A6+0/IWNQ7yD3WCmIIlthVKAuVScSG2hL3Qnw1uPyveg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-24T21:49:27Z"
    mac: ENC[AES256_GCM,data:K6spO69h+0tn0IEyo8is0MGNdxfmtk9ssdiYiimkPk4aY2vU+i5R0XQNhcXNSEzM/hUX35OQ3WcJ05glQcWsJpBKWH8Wmlfb788kqoCUcXGp/t6lCZMyo/f6Qh8xXFhEHRpuja8p29AJ3p0M7T2DjMy+a8D5I6MNrdZFfNZ1DUM=,iv:liXLu7YGFN3fRVqNgTYK3FeU601p5DgNi6lJos03054=,tag:pdE7RBjMK3yD4BhV5GPF6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
