---
# yamllint disable rule:line-length
apiVersion: v1
data:
    auth: ENC[AES256_GCM,data:UswpA+St7dYuvF71ow3U6uh/o9Q0vjdOp9YBOj5hqtdGauui+b5cO4UWF8ns2oApy1ll2OyplF8=,iv:kAJV02WRUqA6KdWKoYwzeC4eYXHoCKf+2VD2DDzjAEA=,tag:/SlVnZHV5/XL57IPdauYbQ==,type:str]
kind: Secret
metadata:
    name: northbound-api-credentials
    namespace: northbound-api
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsS0ZXSEFjU1AwQlRMRUF6
            djdUUHNiaTRLWWkvMWZvTkdMd0R6czA1cDB3CjN3ZnFDazdTY0lrRkVmSE1UOCth
            SHlSQllvMzh0d1UwVEltaHhvNGhIazQKLS0tIHRhcDFLNjRjbnBIOFpDc3VaVThX
            WEIrMHc0WDR6WXE3b1RJdHJGVHFURFEKFvTV3tPOrvCO8NXwPC5VryKUF8Rt9Ozp
            kycaZtBy9wI11mBT0mt+x5glnXWh5KjrN52hozsnkYqIjTWycADH4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-07T11:17:20Z"
    mac: ENC[AES256_GCM,data:DkujfvEbqN32Bw31dE+yY6GIRIrYL8BKQL23qzDMOXWdB8zAW8FE2fDO3YbO6c9+4t77BllmzDNQ69eoltQpMhbnbY1KlUYmhKu+L7+Lce8nNHZKAftCHoA1RbPzUQn7g74aG+K3niVF9ouJ5l7Eks/Vnr9AXP4oLgHxxHMje70=,iv:12fe7btcFfSw7XhmIDXpAup0GFf902iPjPUAN3aefhU=,tag:feClS4eJM4wwSkT1z2/vGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
