---
# yamllint disable rule:line-length
apiVersion: v1
data:
    auth: ENC[AES256_GCM,data:GFyiDLq8r1aYY/kPXtuA/lFl1rpoAZF8oAYa5qzGV3oV+Zgw58nJDKi019hH97WdS3dCRBC1Ru8HiwMo,iv:0SaUvG9oNARk1UiRdvkfJQCUL/l8Vxn3mpso39DDuQg=,tag:h4389cdi+aUohDtUAIEnAw==,type:str]
kind: Secret
metadata:
    name: prometheus-basicauth-credentials
    namespace: prometheus
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTnRiSkMwTzd1VVo3VStR
            RXJCVHpGYnNRYVA0OHhYK3pJWTNoZTYyU0hZCmJHSjdmaXdPVmd6WGtPRURmeGRy
            eGJTbk1tbkUyRUNGTFMrQThBa2YySUkKLS0tIGljeDJEU05vSm5KcXRpb2JOZSt5
            eWlJZFY2Y0h6WitXUmNickhsRkNCcjgKSVrK/zuEIl3JSa0T82ifxbHhp7B6wAD/
            HUFxXZXQS8Gy1Ke41BFlL856ca9I5HnXCZEbTxv4Ie8LBL1NdUFafA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-20T09:49:13Z"
    mac: ENC[AES256_GCM,data:/Ypa3gaibCB8XefybH+p2erz1B6NcD/cw4ayXRSDU098lmjlWeJ0kWv+/o0SdLs0REEj7NJqHVs2Ve6smpX5zF+hOparg7EyEjEFqnMTaga6rUYBu9/TpF81aB62naJ0JRH2JQW66LD/6P5XlpJkJ+B3Buc3XZVdSQ0XFDg1/zY=,iv:1v9IwAM2h2bj6ZdCAwhVjs0ojRGCvD/JmOoz2BU4n8M=,tag:AC3q7Vd+Ne7U/MXkrub+UQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-slack-api-url
    namespace: prometheus
type: Opaque
data:
    backend-v2-notifications.txt: ENC[AES256_GCM,data:Girufp7QuWkSg9ciPw9NxZlD8rbsWd2I+I91FPuAKj1ZaXyD6g9lJNLE5aTW8hxvMyJzt+0ngYMZasJ9YfkbwTJqWzwqIQIMrJa4Vrpbf8SP0LbqFj41ZMzbqy/18n+bKMeXUUTd9bEZREKM,iv:b04XLg/+tjj1kpWgkl7JwE9u6altOHaCsDV/c7Zwsgc=,tag:8Zz43YgvuJEUQhkb7YyClg==,type:str]
    gws-b2-cleanup-notifications.txt: ENC[AES256_GCM,data:sYu+8KnUhE1Y6gSo2AkoFk0QQIPOvXN2M/JJq41rjF2OPvGg9t7x6LKD51GeEWl3qVLQ4a5dNU8SGqYMY1xDqjv6ZnU3jW94gubakfmfJuFN0jsabS89dOUINER86em+93DjoETPDI1v1Au8,iv:PILHLAMokfWHwo9kHwoO83Mrr8P601Pcmx9SLhPvTew=,tag:Qp7Je+y8Z9mLlpwc0ivO/Q==,type:str]
    rook-ceph-alerts.txt: ENC[AES256_GCM,data:nu18VuphyeUdIBEZ9cK9BIn8fHrJ115DNdzik838C/8fbe8SuxxemJzAQgHjhJosXvxoa/PjwcReXRtJF++D8XNZP/9VQnpapwY6mTkYMMIoNkOfxUt8Glqc0iqu2hKGAd2fOaAJXKSVqwV9,iv:NZRu82bk56x1zFte8Ou+krkfuD4e3AHMSQMZUQqhihE=,tag:9LnhC6LSBqlWa84FH7hynA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyclhtdFdJVmwxOE1HYkxL
            cFZPektaVUFqc1BuTUxoRWlmNjlZNTI5MG5NCkFJWlZqZzNFeFpNY1ptWnBXemxz
            aFJsQjRIS0VUQVExc1ZVWERpL3Z3VjAKLS0tIFRxZ2trQWZyaFZ4M2pGd3JQQVht
            Y2g3a2wxTFlrR01BbVg2c1k2QXozWFEK+irjvOzdT3fF+iuaEPAM3xmuSZTgY3vQ
            KYptmYQZJJqj3jPjKTtZo/idTW2nzOALr1B+JuS/ti76C5IPf4jhfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-20T13:59:35Z"
    mac: ENC[AES256_GCM,data:kWqH0rf7MpGyAZQiWWNEU53IQdQO/fMZmG6NS3uJL6sN42fGKGEciKWN5bNTsPcKbe3FQBJw2F+Tcz32DTSQYUlwOwU1Kd4f2wRibqdtyXuJ2gPviC1WIbCu5nvhX/oaSJvv2znRVsEgGQjiq1rxcuV5CQe2natMYPqZVAtfl74=,iv:ezAV3IH5E1bE4NGSgKEa/dRvhDwtAaUm1QQnsnvgQRA=,tag:eloTB8u0bL+JUBsaXgI5fQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
