# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: public-dns-key
    namespace: customer-operators
type: Opaque
data:
    config-snippet: ENC[AES256_GCM,data:j6DH9mwhNu77Svx2cY8m2IHxc7AOlmLKwW/j+JRolEdQF8iJPi5WqPeRUaoT8C0Fnl19AlwmfMDBr1wmlA7taRfdD1X6PiDw/1iCbLAgS2CboOciAEGFnf6Ijf1dJmwIi6P1LFAkOyd/XWDbeAq4ZH7GxW7RquSvFUp19I+7fYqEx4UWQdghHVtlixRa9pez1JZnTr5kVQVPlRl2JufZwleXewHrio0VBq6bU+H1NkrmT0rr7IqCd/nuf3Xoj+vrSZaNoDE+w3+6x4/TVfZIAu9EcGLAUO9AtprbgvunqLVZ56huQCPu/uPLlStbQupSQg0m5KIX8RcPKYqzDVNnJAeGyto6tDor5Y9/NatGph1Vr7y7zSrerqg4xe6L49cOlZ76mDcpqMziT1OpftCAVcKiVFpdmi75OhR7hGm7PjwV4QJyrw1DADxBqtf5MTn3Cv8Qd95ZVh+esz+HXDgLuUSIoQdsFXEMmS2+T8T8mOsauGUxRPrttI6JK5Ch0SqL7zrFbWF5agXAxguAbpBm9IFvF85iEjjgCz/5NvoIOc7QL8dj7TQM7l5jXEtPHqF9ZWNHfTbZIqTtCGQgvT5edAm9yFYVlq0J1YujOkE3gV/qELgRQASfHUVD7cmjAnauoEEvWzuC69mJz4VX1IKZxjKjJeMasPRYGHK8verCfqqWCvsf1tcietGGVne+0r84VQ3QlcvG9aGIU2fDkLSdfYVODj2REvAuG0GBrEfTDySJ+wz/5HFIxccDHqBmilKzjk1j2wGvul20fcReVDB/+o/qKrVjsP1ZInQcwwNv97sEjTbyroNMBaDow8jQAvt4qUjoM51/tsrBIge1nv7O1s/xki8=,iv:vd3lG+bRAkLk06NOe7/mErhJYGLm7hJOoAoTdQ8yDnA=,tag:e+qODjv6rIiCk4sbXQQWQA==,type:str]
    secret: ENC[AES256_GCM,data:Mz/UqJ++2bCjLmKlWeXfFTEHtfxNBZvmZQFnilbjxOnZFWO96rKo96m2EEb/KvBNJKP2ASjnRhtXK0KDpNnWTl69uGheGFv9n12BsMtJSWZnSVTwIU+KV1td35LinX8w1Az9aHw03KJPMh3Mk/ccKLCvK6twj/ajg1G5tQ==,iv:m3wHHvZ0GrjWmee1Es3OsUPY3wc/Hoc/DYdJZ+LEP84=,tag:Z7TlkTPULUBgX/McvKOIkA==,type:str]
    algorithm: ENC[AES256_GCM,data:ri+xHetJknYR5FySHu3QJw==,iv:wlTwuwJ3xpNH1TXzmqrxhmtQp54SwXa4eQjkfXyjMjw=,tag:9qMzLksGY4sJFHySGRqOmA==,type:str]
    name: ENC[AES256_GCM,data:QnBfDVl1sk70mZCt,iv:36UN97m4RnSpqN4h2IK4n1rCnogXjF8dhZX58QVQla0=,tag:I1KHfHX1ZyjERhNnST69uQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SFJvcE1CTkhST0VpQ3VT
            SUNpZGswd2tBQUQ4ZVNRNUs3cVRFclRUdFYwCjRJdmtobEh0T0lFTTVNOS8rN2Ji
            cW5tQjRRYUtyMVZBVWdsSHBlT0IySGcKLS0tIFN5K1l3QUd0OWVjVmZTRURraTNO
            dGEyUXlpTm9EUjVjbGRaeTZrcEg5RXcKHeaylrndtKYaZdVBjiSIMWVU+sDm3OkE
            LbPbeiiDqtkjwfSpNty7PLa480IBJK2vPfcNBINVoINaY+oHKFUfjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-23T14:34:40Z"
    mac: ENC[AES256_GCM,data:WjgALEbuBJFqEtmeOXEJUdEHIQbJDKC6ZRQhIDRVXUZL5qrTHJKh6meqthJzTCvF12xB+F+D88KqsB5k7ukQUuSx7D9qxjlHnsiewJtWg+Yt19wIiTvaifksy20TgnZdeEFvDRbPKxigyr4L3bAmntglCssdp+5o1o7orKocWTo=,iv:dQmsSlRgsrpg+BR09+cvzZkHL8B10gotxaMsvVsXKCA=,tag:onJDVzeSl39NpEh9rY6EZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
