---
apiVersion: v1
kind: Secret
metadata:
    name: snapshot-presigned-key
    namespace: customer-operators
type: Opaque
data:
    key: ENC[AES256_GCM,data:q/4xoyFhAA64Q6NMbQpjcGcHrueo4FMfh3p7MLiAv0A2VGtOCW5p+1CjqZ5sjBXMDa6eRQHH/BxzyhBa9xGVK9s5qB5IAdpNlJ9uVffeEHsg86jFw4H5w/brzCCu8ijCdHHMyIveLvUERmGzVGMQcRQdHwdtmfHUWHnAu8DcoSh4LxmSnCTDwks5VsyYtLm0vjpwPHtiXH7mNGV8kgy0iIA6p4YOlnMmBZlVKizoH8kSCk8rxL5y67bfuYczd0QZK7AfoD2WvwpnvzHZ1H08tLVTGNwRzzPoE2vvDTuYsl+xxeltZzLdNM//tniZSPmqKz1Ut6rdauJSkwwaieeC35YOGLz4sfdAwG2C0qPBE3L5fvSWGOxDNsDpT0gTFYbz61xx9RprKtbEDVlHj2hFS5El7RrZ1OLY8hK+8aO5qead/FGOrh2JvRlqn9tEb826DiZLYNkd5G7D1xqwS5CPeeZi/pyUAD92HxwN9fZVK8hcHJV5hKq2gphTrsyDQpAJx9pJLlLEuVE9VLmmhYqC+4J1qHg=,iv:UjcQvscPGpNl4mS0Hn3ZLCfQ3TU+miHcAOH6FwzYit8=,tag:xnxiUYNVN2oVJfKRh8Av4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVDBWTjRwQUNMMzVJT0di
            SWN6aVMreW5pTzdZSm9TN3Fma1VSS09ZakRzCldyRmd1WkFINExYU095RVk1OU1o
            QTFtOXlXN1h3YzVBSlBvdE50SUMxOXMKLS0tIG40S3NISkh4eFQwOHhUa2dJL29C
            a09zZlNZMUliTjBEdjZoK1kwT3V4K2sKXC/F4GBQYdsFJEean9Nn2YwyP8HCePjE
            TrijU0A3Bo7k3Axd/Ow0tA3WfTRvl4hpb0z8NydrySq4Tpt1zeEenQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-04T15:03:26Z"
    mac: ENC[AES256_GCM,data:sjRlS/W0LOMBs+d7ue00Tb2slUYssOKTNwczWbLiHP6zgQQjU50kcYANPeCdojJ7GWfqHDG5jLkQr/epVRB1U6SYN6hVR0df4QHXoHkDcfzxeaGR5udz7FyQMeGWcwiUeLBQX7aVwv2/bCD54SqpaRlbxMueOGPlbDQAfXTHcQA=,iv:j6Jw4iSdY6qYcjCoixC1xCJO//U7s67iAIOQwFwk5JM=,tag:ZyV96fMqdkFtceZ7Xlvuzw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
