---
# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: ufm-credentials
    namespace: customer-operators
type: Opaque
data:
    username: ENC[AES256_GCM,data:rbvO3FbYHac=,iv:rJRqAlterl4mr72ikIUD5K47Z8NUNAdw9JvnPOwpmZc=,tag:aIIECZOIot3iqboENzvLOA==,type:str]
    password: ENC[AES256_GCM,data:27K9Cxdi1EyVO0EDrXpif3BIyM0RNzNeigkXC3NWTCuKFtEacv3zbw==,iv:R1XTJM+dg96c3D8GxNGOC2dgp7pkRs7Vp9Afq3ZWmIg=,tag:OwSRRkTO5Ni4pUU0PfLrbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcDVHN280aWZjdTNtbTk1
            K1MzSHl3TkhvZ1VGcjErc1A0L2JPejBqc2xvCjAwaThDZ1ZUTXpjamRQYVI2RGZR
            R3l4a1Y4RkVYK3JDajBWZHNvdXNsbFUKLS0tIHNIQms3RloyNXlJSDBpQzl6K1ZI
            SGdiV052L2MwcXJjVVlOeXFqUXVxSHMKmKAGeNMb0dZUvl4+ZxSsIP3GIfwEe3G6
            huGUQywxprdIiWK1hfyE1E0P3xocG0qIpWcIrpvs0X0LU2LpK96zhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-22T00:51:18Z"
    mac: ENC[AES256_GCM,data:iSixNfZjjy8uVa6jGlcDFkoeP6EAu0nwm+WhivxNDFu8/K8QxiD4/84dANPijTH07YvuH//fflgN5uX0IeBo2wWZX4Pbu2cFR7MGsozyjxsbHClPmIXF0VmfOyB18/QNFw7YZycfnYmQbeYzoOkFJzWev27M8GFDjwuxQkFP0vI=,iv:SmBe0uDMCdNR4RldL3HxJiOS2qUOV/oXEpL8ASYE8JI=,tag:9kqQXfMkNrKeKEo+VMSCbg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: ufm-credentials
    namespace: prometheus
type: Opaque
data:
    username: ENC[AES256_GCM,data:rbvO3FbYHac=,iv:rJRqAlterl4mr72ikIUD5K47Z8NUNAdw9JvnPOwpmZc=,tag:aIIECZOIot3iqboENzvLOA==,type:str]
    password: ENC[AES256_GCM,data:27K9Cxdi1EyVO0EDrXpif3BIyM0RNzNeigkXC3NWTCuKFtEacv3zbw==,iv:R1XTJM+dg96c3D8GxNGOC2dgp7pkRs7Vp9Afq3ZWmIg=,tag:OwSRRkTO5Ni4pUU0PfLrbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcDVHN280aWZjdTNtbTk1
            K1MzSHl3TkhvZ1VGcjErc1A0L2JPejBqc2xvCjAwaThDZ1ZUTXpjamRQYVI2RGZR
            R3l4a1Y4RkVYK3JDajBWZHNvdXNsbFUKLS0tIHNIQms3RloyNXlJSDBpQzl6K1ZI
            SGdiV052L2MwcXJjVVlOeXFqUXVxSHMKmKAGeNMb0dZUvl4+ZxSsIP3GIfwEe3G6
            huGUQywxprdIiWK1hfyE1E0P3xocG0qIpWcIrpvs0X0LU2LpK96zhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-22T00:51:18Z"
    mac: ENC[AES256_GCM,data:iSixNfZjjy8uVa6jGlcDFkoeP6EAu0nwm+WhivxNDFu8/K8QxiD4/84dANPijTH07YvuH//fflgN5uX0IeBo2wWZX4Pbu2cFR7MGsozyjxsbHClPmIXF0VmfOyB18/QNFw7YZycfnYmQbeYzoOkFJzWev27M8GFDjwuxQkFP0vI=,iv:SmBe0uDMCdNR4RldL3HxJiOS2qUOV/oXEpL8ASYE8JI=,tag:9kqQXfMkNrKeKEo+VMSCbg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
