apiVersion: v1
kind: Secret
metadata:
    name: vast-credentials
    namespace: customer-operators
type: Opaque
data:
    username: ENC[AES256_GCM,data:1PmpnspjO9zWNawjIWaL5W48HgYyeaV1ZvAfiQ==,iv:zjlR3t5+gCDFT1edMgpObGn9wvC9A7ojAxbiMNFse3s=,tag:kVeSsJqTkNCq/ZkJ6XYt7w==,type:str]
    password: ENC[AES256_GCM,data:f7WLBtOa+Nax9SCEGfIbCg==,iv:iH3ADDaNFEzBVIgH5uRzGLVzpaVLNOPT4wF5duXU0IY=,tag:h/3l50xvg2oxiMXUixMuqw==,type:str]
    enc_key: ENC[AES256_GCM,data:jojqCrLcEtqrHdFU9I6DAtZ6APh2QWvCzDDq91ZTxo9BUllLENLH8jw3LYmaM9K30V2U9p4v7PrJslzG,iv:ApH1DRI/GTkCXgj2O3q8TXp6BvaJwz5at9Ars11ShjM=,tag:/nXKZs28IhWePMzxtWa7lg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VlhpWG94NlZTM0Y5VUhR
            Wm05OTRqTXpGZzNBdmI1QndzSXE5ODEwaFVBCnBqa2NORmMzblJIa09TTnNaVnR1
            N0NpeXBXSG81VVZraWEvT0w1WGhQRlUKLS0tIDJDYWZvZkVJcmVzd3FJMDZjYnlk
            WDBOYTVjVitmYmV6VysrMXcxUUhWdEUKnKTbt5pWJepf5W9KmIecVwIMvDN3ox43
            eooE0xC6lfQfuiORNfXcYYpYHu2/SzH/2tGfSxH1ZCKb65UvTZt/CQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-19T14:55:45Z"
    mac: ENC[AES256_GCM,data:K9NjANrYCScb1ZmOJdWMVd+G51YKewKB55SsY69VVbA72R1a3syFtonrh+0mGkrqgrjqj+238sS5fiznIsZYHEwfxSpMm/i27hceaYHl1XW8UVgXT+RsYS9P7hdnowGieJ7H4LCJ9FfEgAvBxnn0hADpR+QWQfU7xvoHiIJNIVo=,iv:mMgaFvcbQwIjh9JfA0WuQ1nrGAGLGqBcQ+yU9uiiF3Y=,tag:TOWsvBRDSyJW7wWxFElMTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
