---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: smarter-device-manager
  labels:
    app: smarter-device-manager
spec:
  selector:
    matchLabels:
      app: smarter-device-manager
  template:
    metadata:
      labels:
        app: smarter-device-manager
    spec:
      priorityClassName: "system-node-critical"
      containers:
        - name: smarter-device-manager
          image: registry.gitlab.com/arm-research/smarter/smarter-device-manager:v1.20.11
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            limits:
              cpu: 100m
              memory: 15Mi
            requests:
              cpu: 10m
              memory: 15Mi
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: dev-dir
              mountPath: /dev
            - name: sys-dir
              mountPath: /sys
            - name: config
              mountPath: /root/config
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: dev-dir
          hostPath:
            path: /dev
        - name: sys-dir
          hostPath:
            path: /sys
        - name: config
          configMap:
            name: smarter-device-manager-config
      tolerations:
        - key: gpu-host
          operator: Exists
        - key: cpu-host
          operator: Exists
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smarter-device-manager-config
data:
  conf.yaml: |
    - devicematch: ^ipmi[0-9]*$
      nummaxdevices: 20
