# Ideally, we would configure the Image Automations to use harbor as proxy.
# Unfortunately, the image-reflector cannot handle HTTP registries and
# deploying a CA just for harbor was deemed not worth it...
#
# yamllint disable
---
apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:PcYlESv0D83CZLdNaaJi17cg4itqLuYXnoGDnlGEVquM5siAR64wL7sxx/k+sQ3ki/V24a9X7dKPf/NPMSgC0knc3i2EvXdJ2hCwML445/mWZ2oLF4R6wKhyHyPNOZ+G7ueJ7XCyzn6FhUBBZ97KKMQVRhnLj88ETpa554O2aRNUD2Ghp5FyVloyq8z9pfdN9YXNog9DC6KcW4N3Q024NIrKSS2MFWZfF6L1o3wKHlSNaYpNVQh8YrExcVPilivCmVv3K6QNdO5rbnle/lEKnLUOVRKVPxKTXHgUfXEdLB9pwL+ccBGSqPdfllD6u49HELfDaEOv8g7P4JdFoC5DFkNX+bk=,iv:EYZ31Dbn6rOQGkBFnMn9k54hQhWRoL7qskW/W5T3d64=,tag:u+ZGGY3IxkvBH6UIRkgSUQ==,type:str]
kind: Secret
metadata:
    name: image-pull-secret
    namespace: image-automation
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTXQ1YkxMYnNvY0tNTzNp
            RklSUG9lNGdnT0dmZitLbWtxcnhwS3o1eFg0CmVrT0pVVlgyZE9OaDc1MW5TTnZo
            REQ1NkV0TU5jUkp6cU1ha0ZTc080WFUKLS0tIFFiQkFpejUvZTU1eG50OENoRExF
            MnA5bThHaTludnliWnFXUXNJdkR1b2MKvasjNcoFdoYzomd7A2ifhHYt1DQqGcoZ
            +yMGXTel7hEs+xk1F3Kfy/k4Yd3VNIQsImUvOn1V5YxNrD0JXUUjkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-16T08:47:38Z"
    mac: ENC[AES256_GCM,data:dPkCOsstFkK/GyGCukfh/rhWoM0AWkBbhZwbJQJgPmXKU41g2J21I3gzFE7JVOMe0U/cFWdtief90+BQgcK7DagawAU2mfOUC5+Wbp4JsOMusBCkEnmKZPm6BM9RRO994lTP6N2vVpdhru5osmcRVTlX5QtX6MtoY43egJEVE5g=,iv:HN9cA9IrjmKwmAQuvOpBneUcqmEjuH3lY/L5eEizMzg=,tag:d7+ZjtFUQqweRd2qEQpk8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
