---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: customer-floating-ip-operator
  namespace: customer-operators
spec:
  interval: 60m0s
  # yamllint disable-line rule:line-length
  url: oci://harbor.harbor/ghcr.io/gc-private/b2-docker-image-customer-floating-ip-operator/customer-floating-ip-operator-flux
  insecure: true
  ref:
    tag: ${customer_floating_ip_operator_flux:=0.4.2}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: customer-floating-ip-operator
  namespace: customer-operators
spec:
  interval: 60m0s
  sourceRef:
    kind: OCIRepository
    name: customer-floating-ip-operator
  targetNamespace: customer-operators
  path: ./
  prune: true
  wait: true
  timeout: 10m0s
