---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: customer-network-operator
  namespace: customer-network
spec:
  interval: 60m0s
  # yamllint disable-line rule:line-length
  url: oci://harbor.harbor/ghcr.io/gc-private/b2-docker-image-customer-network-operator/customer-network-operator-flux
  insecure: true
  ref:
    tag: ${customer_network_operator_flux:=0.9.2}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: customer-network-operator
  namespace: customer-network
spec:
  interval: 60m0s
  sourceRef:
    kind: OCIRepository
    name: customer-network-operator
  targetNamespace: customer-network
  path: ./
  prune: true
  wait: true
  timeout: 10m0s
