---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loki
  namespace: monitoring
spec:
  targetNamespace: monitoring
  interval: 60m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/loki
  prune: true
  wait: true
  timeout: 10m0s
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
