---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: northbound-api
  namespace: northbound-api
spec:
  interval: 60m0s
  url: oci://harbor.harbor/ghcr.io/gc-private/b2-docker-image-northbound-api/northbound-api-flux
  insecure: true
  ref:
    tag: ${northbound_api_flux:=0.55.1}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: northbound-api
  namespace: northbound-api
spec:
  interval: 60m0s
  sourceRef:
    kind: OCIRepository
    name: northbound-api
  targetNamespace: northbound-api
  path: ./
  prune: true
  wait: true
  timeout: 10m0s
  postBuild:
    substitute:
      environment: ${environment}
      base_domain: ${base_domain}
      b2_dataplane_network: ${b2_dataplane_network}
      placement_options: ${placement_options}
