---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 60m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: rook-ceph
  path: ./apps/rook-ceph/base
  prune: false
  wait: true
  timeout: 10m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 60m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: rook-ceph
  path: ./apps/rook-ceph-cluster/base
  prune: false
  wait: true
  timeout: 10m0s
  dependsOn:
    - name: rook-ceph
  patches:
    - target:
        kind: CephCluster
        name: rook-ceph
        namespace: rook-ceph
      patch: |-
        apiVersion: ceph.rook.io/v1
        kind: CephCluster
        metadata:
          name: rook-ceph
          namespace: rook-ceph
        spec:
          storage:
            nodes: ${rook_ceph_nodes}
