---
# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-slack-api-url
    namespace: prometheus
type: Opaque
data:
    backend-v2-notifications.txt: ENC[AES256_GCM,data:QiWhv9/9dGxvSVCSAWCKNk1DM3ZQsNXAZeEymp4lF23Qydok3xnovJZ1gJPuRnSnHy/lk1xpuEoIf/ctOKMeaunsePWi7aDAoJ7ZE0J8c08bWIoAmOgfbdjb8/o9lWnA07V/kXj+oUo6r8Mp,iv:upwUI7F29vNmf9srAkJDDEeAkF4FY2EjyWgZwxZYimc=,tag:8gnBz4OT/ZatTD6BfE4k1w==,type:str]
    gws-b2-cleanup-notifications.txt: ENC[AES256_GCM,data:7TIkoSvwKcAPwgPqljfcYV6ZVZ1heJY+qgTZtALPHtUlPaomCZxjX+l/J66LBrsuXaa5wI13ZEvR4U0aa1Bt0/RZXi8T9LUgZVba/j79VfPBBpv4U9YQDf8NGIhaXLDs34t+6y7v6RWGboP7,iv:j9tvPHExkNTlnJcF1zHeEEjCmZw5w9MnGeJDvOKwlPM=,tag:ZGuHstxBitdtZddOYlA6hQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZ2hFbTVOd21XaUNiRHh0
            d0hQa3lYNUxRYzRvWi9HYm1CeHRjdElVbzFzCmhwdVpIN2FCVXF4dmEvbjFqNXFi
            R3laV1lmZHUraGM1RUFMWW5KS1BlajQKLS0tIGNKcDJVWkNXU3lHVDFlL1dlclNv
            Nk5PQ3B0cmt5RndDVmFncFJXcXJtc1EKdYRfbHDWbt0W/nlcBlkxSaly35FLC+3J
            3AQ+E/ExRbSy/JT5blITZvhpzQACevG+YclUCV80Lux1Of5gE10dYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-04T18:29:54Z"
    mac: ENC[AES256_GCM,data:x651h0JJLsq1uTOj/W9Y632/6uc7SMfaD69uWHaDG+grUcf5B4EkwX+vTrd+qzedeZ1wgXEpfaYvZBS+CJbIGLrnM1jTnc0HQDNAlOAIcl+83ruqmKXHcyu6PMzvsL64+Vc6agDVzuvOrS7KwRSoPJ9gcWbR0nsPajLWXJ9oVNU=,iv:JbC9R2NCNrFstRp/Ps2IhUEUH0zJv7oWcMmPW/dRcV0=,tag:d4+iU+A9/1swSAQ9gevOZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
