---
# yamllint disable rule:line-length
apiVersion: v1
data:
    ceph.conf: ENC[AES256_GCM,data:J/9VBpT7NXzLB67cn1d0f6SlgKhWcyf4mPUOtYQJySAuFUYYoYI3Q44mj+wUMflinNR4aK4MZEKrAfYqRqSDUshbHKdP+3kafKWUWLZaT6RB0n83nLOPTJLo9AUnprMyFdBKqqAXBvCHsuO5MPNhoxc1IlsPMGI2hSoMo76bqJS9YhWaWsBA3SudEw9brsIszyWx9cuYANwbLvwo/rI62bQM/nt4vM/7MbUCyDmioLlWPQlcCQAXSeFXIJrV4WSvxJUM1hcZbOj2i6qDP4BNzRFKTwGfzBXuk4hI7+W+AxM09WH7gmVeo7o/o6gEA1W1fhpyZr1rqEAD5/4vWQg2eyPDOeRkUV+llaE78q9en/3/Kgohz2RGIX7ockj6aU9kF/FwJLoImdpjh7K2TrRBtJm75QRRpXTIFFejvuBaWT65NZw7DGfyYoqkqeP3YlFrtHt+VL8z3PMwiGQkPuc/WcbmxsJ996nHQwZ7pw==,iv:8RnsCrsrrl98YUFW38Y/c+fsMfz+UW++r0IVnQN95rU=,tag:hUQQii5sFO9Awv+uQ/lSOg==,type:str]
    unreal-uuid-ssd.conf: ENC[AES256_GCM,data:46/AVa+H9SXw9TNA85+LHqhRu+50F0vvOvsF5iIyHRUe9BBrioFm3Z8cJU36wArRJytF8KzhM7w8hsUCIkndPLVvbg8VIan0AG+cOX854+uzK56RVbZgFO/UHwkJsnj2j/Nedir/NAY8s451C4bNLiABkWR2mi/PsGrvPgwQZL9rBsDC29fX9tJ4hWql1A4N+7fjNBjjW2nEjfZLs1yBTMV5gTqYazOPwEpD+bRQVBvle5Jq6yDFsp/9aBvvZOSjyY/8JRx9SU7NYF1lak3gqfc+ZCrdHIbrl3JQtn/H9omiO072OXnGUK8ArtBPZRBjUkWTlUACk5ZUHT+Fpg9BOpWBB5WdcpP8IdveI7VIomsXLyIslfsURcq2CuyG06Z0uj31PKAvxw7H/KzPjLKZxoOWfO/F0ezcV2kfcl/RPlH8ljtHKMJJDQMv4wdLI+L7GSscV2Iqw28uU5y9SKYBKEUTwWn7H5LZDJovvQ==,iv:eGrP8aV1V9gquj8iP5vKDaBwu93n7nbRaMRX5Euabb8=,tag:oSYnfal/F+2fTv3ylHB4FA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: customer-volume-ceph
    namespace: customer-operators
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSnk4N3ZjWlI0TXRXdWtW
            ODE5c01DZERXem0zdS9TZ2ZnWCtDSnlydlJjCkZwY0VHTDZKNDkybkt4VmpURVVD
            ZElvUFpJQjNNSlJPQXZBMlNkMS9uVUUKLS0tIHBBcndOaVVTaWpRTFdoSlFDQjJF
            cmUxeXdYc2FGTllKTXRvVHMzczlRRFkKFI6hGociNsYv/MOaBdTqP+P2wJ5y92iD
            ZgqMUA8tqTkwW4Olur4I5UYjDO6fDAMRQktglKmZxz+L1HKou1JmQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-28T14:09:23Z"
    mac: ENC[AES256_GCM,data:UAIBxIaIeimChDC5RLsjbt88amyZUjqvL0xXsqPtkPE9BJg1rZpVmrjzpJvdtplDvlEge4GgEdceS/QlOm0LScyFWihF8mewOho53dbWRP60OYg8ijmKw5zYVJaJWTjdbW4bpYieJI/tTwpsI7GDfx8haufAwdSXPLwUuFBmUjs=,iv:Alx2a3iB9jWnFRM4C1DaqoFTafDn5Rxltwdb41U4O6o=,tag:TdS5ykixp1xv6ryCG/B71w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
