---
# yamllint disable rule:line-length
apiVersion: v1
data:
    auth: ENC[AES256_GCM,data:HXJ9ECvcadswEsygffSrzy5tHIhSWzCfXU6phs0wputWOAIFd7reQ0HOJg+c0U7qLLJWUpEUYmE=,iv:PKcZhT018o5pJ9cCwNlR89rL4zvt2rJFS+OUoc1TlIc=,tag:PmpWABZIC5AHMIRgcVTPsw==,type:str]
kind: Secret
metadata:
    name: northbound-api-credentials
    namespace: northbound-api
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWWxNbWNySGgwRlpmQXJR
            UVNxcEFVNUVscTg1eUdVKzV0dWJMTUVFdFQwCnpuQXhFSmRQNHBvVi9QNHEwcVp0
            TWxUN2NGdlNoeXNJYTdvaGp6UWtXOG8KLS0tIHE5TiswNUNEcElZSGVkbXNNSHJ6
            M3Ztbzc1Z3pydUNScjV3cE1DYUV1dW8KX3rNDGUY4UmfAiRWO832xT41NXCOWxBQ
            avp0P0uQwknotj2cxHl41Ma6iEIJyI9lf61qJJAPxNqDlZWCk9t8rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-07T11:17:16Z"
    mac: ENC[AES256_GCM,data:J8ZlSC8jb+fu1rC1wELt8zNCvjAbQrkDZ9TOfh9Q3epJwcWCRVtSD+taQgGwASwK5ViAybjBIEctfIe8eY+0r8GcFM6V7YQVxjSQ82B7i6zVKJFb3g8B23DXCTTRBnvSnpnhZjmQc9P6K7E6C2McjrE1mLOM/wTwI+0IhSAkAn4=,iv:u6OLfVQwGsE55h1eJ3dNZ0qYwrdjQTod5LF0b7JqRfY=,tag:zxA+qOwF+ijBFYlNWX7OTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
