---
# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-slack-api-url
    namespace: prometheus
type: Opaque
data:
    backend-v2-notifications.txt: ENC[AES256_GCM,data:0x0rQtxGX0KAivrlUGczeAuDUN6xCp4zPsOQ0XPt6F9+7rY6gHhM3XlE45q/EyjsXXCGxrBJdRpJKepPbHjvk3CpCqMNoifFfxPZWYTGfhtV0oY6eDwleTdQPq1DMsF0b5VAYfVr7vtD6zis,iv:Bl3LeGGdFg1Uc6K3kg2f5L7omcjls0p3iXwpwItuCJs=,tag:4HKxoQ6zrWFLK24gxHrDMg==,type:str]
    gws-b2-cleanup-notifications.txt: ENC[AES256_GCM,data:ZeXehJnBMfsFUDYEK34MfSBjI04qCqmPlppQGTGwhyI+Y+jTiFky7nKidzy61WAic5fN2JEc2ZuMNZhDlDh0WAuLJoeH/MsDzJths7h3eyY4fgmsJFpucdiZzxu5CaNoh2qShJrDVDVpR2UH,iv:LSNfQo0eSWeYtJZhRwUPc5Tuvl3eEeBVjHlPx0H6omo=,tag:wSSfrMP1ueQAOaBhbcVDBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMUZBRjJaalEvalJkRGxy
            N2IwWnFiOWI3OFJibUdKY1ZwaGJNVU9DRFh3Ckl0M2E4Z0JVekxIK2lQS3V5NmhY
            NWt4c09xOFJqR0YvZ2M4cjliZXVBVFkKLS0tIHhQNXJrVUhIYlNNRjg5Y1EwQ0lG
            c3QyeWJzeGxhVjF0d2dYblBKaDNsbkEKcpkeJzKytnj4y8TEgoeQkBX3zREgBJHu
            aayOtlAFaE8gsXTKGNJj24/8VfIHEm354wwXhFxmDx3PWBuXcQUW1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-04T18:30:47Z"
    mac: ENC[AES256_GCM,data:wo8lprnW3f0WsMSx/YPc/Wa9zuNdSfE8l/hemT+lf3UKzbz3S0mS2/HOEoXwy/xxWflV7+n8dBTJ0CKCpyocyuSkFlxrpQ+JoRQi+S4Bi5mimaVdj6CZegOE+C9kFfimwbtmEb8JvIcnYGivZaPyxONiQ7cWNUhaya0/0O+/RC4=,iv:1rJ9wmrcewNOG2huYSgJhofYIdbLzr+donl+2nOg6Kg=,tag:r6YhzvKA8dvglJLoRPZr7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
