---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfsen
  namespace: nfsen
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  storageClassName: fs-replicated2
