# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.27.0
  name: alertmanager-main
  namespace: prometheus
stringData:
  alertmanager.yaml: |-
    "global":
      "resolve_timeout": "5m"
    "inhibit_rules":
    - "equal":
      - "namespace"
      - "alertname"
      "source_matchers":
      - "severity = critical"
      "target_matchers":
      - "severity =~ warning|info"
    - "equal":
      - "namespace"
      - "alertname"
      "source_matchers":
      - "severity = warning"
      "target_matchers":
      - "severity = info"
    - "equal":
      - "namespace"
      "source_matchers":
      - "alertname = InfoInhibitor"
      "target_matchers":
      - "severity = info"
    "receivers":
    - "name": "Default"
    - "name": "Watchdog"
    - "name": "Critical"
    - "name": "null"
    - "name": "slack-notifications"
      "slack_configs":
      - "api_url_file": "/etc/alertmanager/secrets/alertmanager-slack-api-url/backend-v2-notifications.txt"
        "channel": "#b2_alerts_${environment}"
        "send_resolved": true
        "text": "{{ range .Alerts }}• <https://alertmanager.${environment}.b2.${base_domain}/#/alerts?filter=%7B{{ $first := true }}{{ range $key, $value := .Labels }}{{ if $first }}{{ $first = false }}{{ else }},{{end}}{{ $key }}%3D\"{{ $value }}\"{{ end }}%7D|{{ .Labels.alertname }}>{{ if .GeneratorURL }} (<{{ .GeneratorURL }}|:chart_with_upwards_trend:>){{ end }}: {{ .Annotations.description }} <https://alertmanager.${environment}.b2.${base_domain}/#/silences/new?filter=%7B{{ $first := true }}{{ range $key, $value := .Labels }}{{ if $first }}{{ $first = false }}{{ else }},{{end}}{{ $key }}%3D\"{{ $value }}\"{{ end }}%7D|Silence this alarm.>\n{{ end }}"
        "title": ":${environment_flag_emoji}:${environment}: {{ .Status | toUpper }} - {{ if eq .Status \"firing\" }}{{ .Alerts.Firing | len }}{{ end }} {{ .CommonLabels.severity }}(s) in namespace {{ .GroupLabels.namespace }}"
        "title_link": "https://alertmanager.${environment}.b2.${base_domain}/#/alerts?receiver=slack-notifications"
    - "name": "slack-resource-cleanup-notifications"
      "slack_configs":
      - "api_url_file": "/etc/alertmanager/secrets/alertmanager-slack-api-url/gws-b2-cleanup-notifications.txt"
        "channel": "#gws-b2-cleanup-notifications"
        "send_resolved": true
        "text": "{{ range .Alerts }}<https://alertmanager.${environment}.b2.${base_domain}/#/alerts?filter=%7B{{ $first := true }}{{ range $key, $value := .Labels }}{{ if $first }}{{ $first = false }}{{ else }},{{end}}{{ $key }}%3D\"{{ $value }}\"{{ end }}%7D|{{ .Labels.alertname }}>{{ if .GeneratorURL }} (<{{ .GeneratorURL }}|:chart_with_upwards_trend:>){{ end }}: {{ .Annotations.description }} <https://alertmanager.${environment}.b2.${base_domain}/#/silences/new?filter=%7B{{ $first := true }}{{ range $key, $value := .Labels }}{{ if $first }}{{ $first = false }}{{ else }},{{end}}{{ $key }}%3D\"{{ $value }}\"{{ end }}%7D|Silence this alarm.>\n{{ end }}"
        "title": ":${environment_flag_emoji}:${environment}: {{ .Status | toUpper }} - {{ .CommonLabels.severity }} in namespace {{ .GroupLabels.namespace }}"
        "title_link": "https://alertmanager.${environment}.b2.${base_domain}/#/alerts?receiver=slack-resource-cleanup-notifications"
    - "name": "slack-rook-ceph-notifications"
      "slack_configs":
      - "api_url_file": "/etc/alertmanager/secrets/alertmanager-slack-api-url/rook-ceph-alerts.txt"
        "channel": "#rook-ceph-alerts"
        "send_resolved": true
        "text": "{{ range .Alerts }}<https://alertmanager.${environment}.b2.${base_domain}/#/alerts?filter=%7B{{ $first := true }}{{ range $key, $value := .Labels }}{{ if $first }}{{ $first = false }}{{ else }},{{end}}{{ $key }}%3D\"{{ $value }}\"{{ end }}%7D|{{ .Labels.alertname }}>{{ if .GeneratorURL }} (<{{ .GeneratorURL }}|:chart_with_upwards_trend:>){{ end }}: {{ .Annotations.description }} <https://alertmanager.${environment}.b2.${base_domain}/#/silences/new?filter=%7B{{ $first := true }}{{ range $key, $value := .Labels }}{{ if $first }}{{ $first = false }}{{ else }},{{end}}{{ $key }}%3D\"{{ $value }}\"{{ end }}%7D|Silence this alarm.>\n{{ end }}"
        "title": ":${environment_flag_emoji}:${environment}: {{ .Status | toUpper }} - {{ .CommonLabels.severity }} in namespace {{ .GroupLabels.namespace }}"
        "title_link": "https://alertmanager.${environment}.b2.${base_domain}/#/alerts?receiver=slack-rook-ceph-notifications"
    "route":
      "group_by":
      - "namespace"
      "group_interval": "5m"
      "group_wait": "30s"
      "receiver": "slack-notifications"
      "repeat_interval": "12h"
      "routes":
      - "matchers":
        - "alertname = Watchdog"
        "receiver": "Watchdog"
      - "matchers":
        - "alertname = InfoInhibitor"
        "receiver": "null"
      - "group_by":
        - "..."
        "matchers":
        - "channel = resource-cleanup-notifications"
        "receiver": "slack-resource-cleanup-notifications"
        "repeat_interval": "12h"
      - "group_by":
        - "type"
        "matchers":
        - "namespace = external-prometheus"
        - "channel = rook-ceph-notifications"
        "receiver": "slack-rook-ceph-notifications"
        "repeat_interval": "24h"
type: Opaque
