---
apiVersion: v1
kind: Service
metadata:
  name: external-ufm
  namespace: prometheus
  labels:
    app: external-ufm
spec:
  ports:
    - name: http-metrics
      port: 9001
      protocol: TCP
      targetPort: 9001
  type: ClusterIP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-ufm
  namespace: prometheus
  labels:
    app: external-ufm
subsets:
  - addresses:
      - ip: ${ufm_address:=192.0.2.0}
    ports:
      - name: http-metrics
        port: 9001
        protocol: TCP

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-ufm
  namespace: prometheus
  labels:
    app: external-ufm
spec:
  namespaceSelector:
    matchNames:
      - prometheus
  selector:
    matchLabels:
      app: external-ufm
  endpoints:
    - port: http-metrics
      path: /metrics
