---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  interval: 30m
  url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  targetNamespace: node-feature-discovery
  releaseName: node-feature-discovery
  interval: 5m
  chart:
    spec:
      chart: node-feature-discovery
      version: ">=0.14.0 <0.15"
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: node-feature-discovery
      interval: 1m
  values:
    gc:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
    master:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
    worker:
      tolerations:
        - operator: Exists
      config:
        core:
          labelSources: ["custom"]
        sources:
          custom: []
