# yamllint disable rule:line-length
---
apiVersion: v1
data:
    auth: ENC[AES256_GCM,data:VHC2mg6lKSk5WC8c0wgnygc1ILynju4Yn+oX/9jNYGWzpsxAkh7w7rtNbHGkX38b/CdmHhpKHr8=,iv:1DFe11GUhwYNr3XbU/oV/132aR17u6j2Ud+Cy4C88mY=,tag:rhIE8lDsbA17+AfrHrkKDA==,type:str]
kind: Secret
metadata:
    name: pypi-server-credentials
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pph82z80u4wlc3flugq509cnfg7hp9054xyprjwv9sqkhvvfndhqjdy89f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwT2FFVzVEejlseEFlR1hC
            Y2lrcGtOdlpnc0l0OERnaGtDb0FVRUtaQnowCkc3elNwamhBbzlScWkwV2d2blNM
            TkJueU5OSGhJZGZHV0s2TldHeWQyN2MKLS0tIDF0T2VYNzhTUmVROU41T3VZR3Jr
            NjZyamNGWVlmclFoVFBDcjFQU3VnTkUKog5wizvCiVU8ovrL0b/ZJDgTFWtt9hYW
            fxOXBf+KV0p465X7XfAS5WaeLG17JsaRJQ4qGLRXg1svSW5k9SACpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-02T18:01:38Z"
    mac: ENC[AES256_GCM,data:Msm23hJRkXbUD+EvHJcOCfcJibnDlzvJwlCr4oioaacWpF5lpizJ/5tLMRVOkow5Z1d2cfk7YK2EC22ufKKwHRAPw40cko4aatbu+NttXp3UR0lf3YJPHTbOEHEkIlVgly1Nbtfl7dGj1rb2UBvgh9m2Vn3LwJviXnp8vtIx4bk=,iv:9Q5RpqVRitsNq8rrPmuqSAKmStKQkGYxudwfRn4ikHQ=,tag:sjN3NvatvmGucOh2ygf8nA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
