---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-dns01-cloudflare
spec:
  acme:
    email: b2@genesiscloud.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns01-cloudflare-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: dns01-cloudflare-api-token
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01-cloudflare-prod
spec:
  acme:
    email: b2@genesiscloud.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns01-cloudflare-prod-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: dns01-cloudflare-prod-api-token
              key: api-token
